project:
  type: website
  output-dir: docs

lang: ja

website:
  title: "Causal Inference@Kobe"
  site-url: "https://www.jaysong.net/kobe-ci/"
  page-navigation: true
  favicon: figs/favicon.png
  page-footer: 
    left: "© 2025, <a href='https://www.jaysong.net' target='_blank'>Jaehyun Song</a>. Powered by <a href='https://quarto.org/' target='_blank'>Quarto</a>" 
    right:
      - icon: house-fill
        href: https://www.jaysong.net
      - icon: github
        href: https://github.com/JaehyunSong
  navbar:
    logo: figs/logo.png
    search: true
    background: "#1955A6" # royal blue
    pinned: true
    left:
      - sidebar:syllabus
      - sidebar:intro
      - sidebar:material
    right: 
      - icon: terminal
        href: https://jupyter.cs.rcos.nii.ac.jp/
        target: _blank
      - icon: book
        href: https://www.jaysong.net/RBook/
        target: _blank
  sidebar:
    - id: syllabus
      title: "シラバス"
      style: "docked"
      contents: 
        - syllabus/syllabus.qmd
        - syllabus/dataset.qmd
    - id: intro
      title: "Rの使い方"
      style: "docked"
      contents:
        - intro/install.qmd
        - intro/project.qmd
        - intro/file.qmd
        - intro/filesystem.qmd
        - intro/packages.qmd
    - id: material
      title: "講義資料"
      style: "docked"
      contents:
        - material/intro_rct.qmd
        - material/matching.qmd
        - material/did.qmd
        - material/rdd.qmd
        #- material/iv.qmd
  google-analytics: "G-9F94XL4N4M"
  twitter-card:
    title: Jaehyun Song, Ph.D.
    description: Causal Inference@Kobe
    card-style: summary
    creator: "@Tintstyle"
    site: "@Tintstyle"
    image: "imgs/favicon.png"
  open-graph:
    title: Jaehyun Song, Ph.D.
    description: Causal Inference@Kobe
    image: "imgs/favicon.png"

format:
  html:
    theme: 
      light: [a11y, r4ps.scss]
    toc-depth: 3
    link-external-newwindow: true
    code-annotations: hover
    mainfont: "Noto Sans JP"
    sansfont: "Noto Sans JP"
    monofont: "Noto Sans Mono"
    header-includes: |
      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet"> 
      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Mono&display=swap" rel="stylesheet"> 

knitr: 
   opts_chunk: 
     fig.align: "center"
     dev: "ragg_png"

execute:
  freeze: auto