---
title: "本講義について"
toc: true
toc-title: "目次"
---

```{r}
#| include: false
knitr::opts_chunk$set(fig.align = "center",
                      dev       = "ragg_png")
```

## 概要

* 科目名: 計量政治学方法論 I (実証分析と方法)
* 講師: 宋財泫 (ソン ジェヒョン)
* 所属: 関西大学総合情報学部
   * E-mail: song [*at*] kansai-u.ac.jp
   * Homepage: <https://www.jaysong.net>
* 時間: 2021年9月1,2,3,13,14日2∼4限目
* 教室: フロンティア館 304 教室

## 授業の内容

　本講義は、近年政治学において関心が高まっている「因果推論」を行うための諸手段を 理解・習得することを目的とする。最初に、最良の因果推論とも称される RCT(ランダム 化比較試験)を説明し、RCT が不可能な際の手法としてマッチング、回帰不連続デザイ ン、差分の差などを紹介する。

## 評価

* 授業貢献度 30%
   * 授業への参加度、質問など
* 期末レポート 70%
   * 期末レポートの内容は初回の授業で紹介する

## 履修上の注意

　統計学に関する基礎知識が必要である。目安は母平均の差の検定、および線形回帰分析が理解でき、統計ソフトウェアで実行・解釈が可能なレベルである。

　本講義における共通言語はRである。Rの使い方に関しては既にインターネット上に膨大な情報がある。[宋](https://www.jaysong.net)と[矢内勇生](https://yukiyanai.github.io/)(高知工科大学)が執筆中の以下の資料(無料で閲覧可能)を参照することも1つの選択肢である。

* 宋財泫・矢内勇生. 『[私たちの R: ベストプラクティスの探究](https://www.jaysong.net/RBook/)』(web-book)
   * Rの導入方法は講義中、宋が解説する。

　統計学および定量的分析、Rの使い方については以下の書籍を講義開始日までに読んで
おくことを強く推奨する。

* 浅野正彦・矢内勇生. 2019『[Rによる計量政治学](https://www.amazon.co.jp/dp/4274223132)』オーム社.

　R スクリプト作成の際、{tidyverse} というパッケージ群を積極的に活用する。この パッケージには {dplyr}、{ggplot2} などのパッケージが含まれている。各パッケージの 使い方を習得するには以下の教材を推奨する。

* Wickham, Hadley and Grolemund, Garrett. 2017. [*R for Data Science: Import, Tidy, Transform, Visualize, and Model Data,*](https://www.amazon.co.jp/dp/1491910399/) O’Reilly. ([邦訳](www.amazon.co.jp/dp/487311814X/)あり/[原著](https://r4ds.had.co.nz)はインターネットから無料で閲覧可)
* 松村優哉・湯谷啓明・紀ノ定保礼・前田和寛 . 2021. 『[改訂2版 Rユーザのための RStudio[実践] 入門—tidyverseによるモダンな分析フローの世界—](https://www.amazon.co.jp/dp/4297121700/)』技術評論社.

## 教科書・参考書

以下は本書の内容を(一部)カバーする書籍の目録である。必ずしも購入する必要はないが、予習・復習において適宜参照することを推奨する。

* 因果推論の理論と実例
   * **【AP 2008】** Angrist, Joahua D., and Jorn-steffen Pischke. 2008. [*Mostly Harmless Econometrics: An Empiricist’s Companion.*](http://amzn.asia/d/2TJ1HXE) Princeton University Press.
      * 『[「ほとんど無害」な計量経済学―応用経済学のための実証分析ガイド](http://amzn.asia/d/3JwCmNG)』 (翻訳はかなり有害)
   * **【AP 2014】** Angrist, Joahua D., and Jorn-steffen Pischke. 2014. [*Mastering ’Metrics: The Path from Cause to Effect.*](http://amzn.asia/d/fIkurDl) Princeton University Press.
   * **【森田 2014】** 森田果. 2014.『[実証分析入門—データから「因果関係」を読み解く作法](http://amzn.asia/d/g0ADpxT)』日本評論社.
   * **【中室・津川 2017】** 中室牧子・津川友介. 2017.『[「原因と結果」の経済学—データから真実を見抜く思考法](http://amzn.asia/d/gQN4bLu)』ダイヤモンド社.
   * **【伊藤 2017】** 伊藤公一郎. 2017.『[データ分析の力—因果関係に迫る思考法](http://amzn.asia/d/avVVT5S)』光文社新書.
   * **【松林 2021】** 松林哲也. 2021.『[政治学と因果推論](https://www.amazon.co.jp/dp/4000269992/)』岩波書店.
* 理論+R
   * **【星野・田中 2016】** 星野匡郎・田中久稔. 2016.『[Rによる実証分析—回帰分析から因果分析へ—](http://amzn.asia/d/0LFlZqm)』オーム社.
   * **【安井 2020】** 安井翔太. 2020. 『[効果検証入門—正しい比較のための因果推論/計量経済学の基礎](https://www.amazon.co.jp/dp/4297111179)』技術評論社.
   * **【Cunningham 2021】** Cunningham, Scott. 2021. [*Causal Inference: The Mixtape.*](https://mixtape.scunning.com/) Yale University Press.
   * **【高橋 2022】** 高橋将宜. 2022. 『[統計的因果推論の理論と実装](https://www.amazon.co.jp/dp/4320112458/)』共立出版.

### 本講義との関係

||Intro/RCT|Matching|Diff-in-Diff|RDD|IV|
|:---|:---:|:---:|:---:|:---:|:---:|
| AP 2008 |Ch.2|Ch.3|Ch.5|Ch.6|Ch.4|
| AP 2014 |Ch.1-2||Ch.5|Ch.4|Ch.3|
| 森田 2014 |第16章||第18章|第22章|第20章|
| 星野・田中 2016 |第1-8章|第9章||第10章|第11章|
| 中室・津川 2017 |第1-3章|第7-8章|第4章|第6章|第5章|
| 伊藤 2017 |第1-2章||第5章|第3章||
| 安井 2020 |第1章|第2-3章|第4章|第5章||
| Cunningham 2021 |Ch.2-4|Ch.5|Ch.8-10|Ch.6|Ch.7|
| 松林 2021 |第1-5章||第8章|第6章|第7章|
| 高橋 2022 |第1-3章|第4-12章||第15-18章|第13-14章|

## 講義内容・参考文献

### 1日目：因果推論の考え方

* Textbook
   * Imbens, Guido W., and Donald B. Rubin. 2015. [*Causal Inference for Statistics, Social, and Biomedical Sciences.*](http://amzn.asia/d/4hiunWS) Cambridge University Press. (Ch. 1 and 2)
   * Hernan, Miguel A., James M. Robins. 2020. [*Causal Inference.*](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/) Chapman & Hall/CRC. (Ch. 1)
* Article
   * Holland, Paul W. 1986. "[Statistics and Causal Inference](https://www.jstor.org/stable/2289064)." *Journal of the American Statistical Association,* 81: 945--960.
   * Marini, Margaret Mooney, and Burton Singer. 1988. "[Causality in the Social Sciences](https://www.jstor.org/stable/271053)." *Sociological Methodology,* 18: 347--409.
	 *  Rubin, Donald B. 2005. "[Causal Inference Using Potential Outcomes: Design, Modeling, Decisions](https://www.jstor.org/stable/27590541)." *Journal of the American Statistical Association,* 100: 322--331.
   * Brady, Henry E. 2008. "[Causation and Explanation in Social Science](http://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780199286546.001.0001/oxfordhb-9780199286546-e-10)." In Janet M. BoxSteffensmeier, Henry E. Brady, and David Collier, eds. *The Oxford Handbook of Political Methodology.* Oxford University Press. (Ch. 10)
   * Keele, Luke. 2015. "[The Statistics of Causal Inference: A View from Political Methodology](https://www.cambridge.org/core/journals/political-analysis/article/div-classtitlethe-statistics-of-causal-inference-a-view-from-political-methodologydiv/314EFF877ECB1B90A1452D10D4E24BB3)." *Political Analysis,* 23: 313--335.
* Monograph
   * 岩波データサイエンス刊行委員会. 2016.『[岩波データサイエンス Vol.3](http://amzn.asia/d/5zbJ3iw)』岩波書店.

### ランダム化比較試験とLab Session

履修者全員がRの操作に慣れていると判断した場合、Lab Sessionは省略し、最終日に操作変数法の講義を行う。

* Textbook (RCT)
   * Imbens, Guido W., and Donald B. Rubin. 2015. [*Causal Inference for Statistics, Social, and Biomedical Sciences.*](http://amzn.asia/d/4hiunWS) Cambridge University Press. (Part II)}
   * Hernan, Miguel A., James M. Robins. 2020. [*Causal Inference.*](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/) Chapman & Hall/CRC. (Ch. 2)
* Textbook (R Language)
   * 飯田健. 2013.『[計量政治学](http://amzn.asia/d/8FE3FxN)』共立出版
   * Lander, Jared P.. 2017. [*R for Everyone: Advanced Analytics and Graphics (2nd Edition).*](http://amzn.asia/d/0Y4Dy50) Addison-Wesley Professional.
      * 『[みんなのR 第2版](https://www.amazon.co.jp/dp/4839962154/)』
   * Imai, Kosuke. 2017. [*Quantitative Social Science: An Introduction.*](http://amzn.asia/d/fSENuD5) Princeton University Press.
      * 『社会科学のためのデータ分析入門 ([上](http://amzn.asia/d/6uRniTe)) / ([下](http://amzn.asia/d/cvcCUy2))』
   * Wickham, Hadley, and Garrett Grolemund. 2017. [*R for Data Science: Import, Tidy, Transform, Visualize, and Model Data.*](http://amzn.asia/d/6TgCVvd) O'Reilly Media.
      * 『[Rではじめるデータサイエンス](http://amzn.asia/d/54NWHHq)』
   * 高橋康介. 2018.『[再現可能性のすゝめ―RStudioによるデータ解析とレポート作成](http://amzn.asia/d/e94WRoQ)』共立出版
   * 松村優哉・湯谷啓明・紀ノ定保礼・前田和寛. 2018.『[RユーザのためのRStudio[実践]入門―tidyverseによるモダンな分析フローの世界―](http://amzn.asia/d/1huN4Ss)』技術評論社.
* Article
   * Bertrand, Marianne, and Sendhil Mullainathan. 2004. "[Are Emily and Greg More Employable Than Lakisha and Jamal? A Field Experiment on Labor Market Discrimination.](https://www.aeaweb.org/articles?id=10.1257/0002828042002561)" *American Economic Review,* 94 (4): 991-1013.
   * Druckman, James N., Donald P. Green, James H. Kuklinski, and Arthur Lupia. 2006. "[The Growth and Development of Experimental Research in Political Science.](https://www.cambridge.org/core/journals/american-political-science-review/article/growth-and-development-of-experimental-research-in-political-science/4381F50C6A43ED85AF8B973326BC546A)" *American Political Science Review,* 100(4): 627-635.
   * Tomz, Michael. 2007. "[Domestic Audience Costs in International Relations: An Experimental Approach.](https://www.cambridge.org/core/journals/international-organization/article/domestic-audience-costs-in-international-relations-an-experimental-approach/DE9C218365E2AF849FC6ECF67CCC45F1)" *International Organization,* 61 (4): 821-840.
   * Gerber, Alan S., Donald P. Green, and Christopher W. Larimer. 2008. "[Social Pressure and Voter Turnout: Evidence from a Large-Scale Field Experiment.](https://www.cambridge.org/core/journals/american-political-science-review/article/social-pressure-and-voter-turnout-evidence-from-a-large-scale-field-experiment/11E84AF4C0B7FBD1D20C855972C2C3EB)" *American Political Science Review,* 102 (1): 33-48.
   * Imai, Kosuke, Gary King, and Elizabeth A. Stuart. 2008. "[Misunderstandings between Experimentalists and Observationalists about Causal Inference.](https://www.jstor.org/stable/30130768)" *Journal of the Royal Statistical Society. Series A,* 171(2): 481-502.
   * de Rooji, Eline A., Donald P. Green, and Alan S. Gerber. 2009. "[Field Experiments on Political Behavior and Collective Action.](https://www.annualreviews.org/doi/abs/10.1146/annurev.polisci.12.060107.154037?journalCode=polisci)" *Annual Review of Political Science.* 12: 389-395.
   * Palfrey, Thomas R. 2009. "[Laboratory Experiments in Political Economy.](https://www.annualreviews.org/doi/abs/10.1146/annurev.polisci.12.091007.122139)" *Annual Review of Political Science,* 12: 379-388.}
      * 谷口尚子. 2014. 「政治学における実験研究」『選挙研究』30 (1): 5-15.
* Monograph
   * 河野勝. 2007. 『[社会科学の実験アプローチ](http://amzn.asia/d/681CBSr)』勁草書房.
   * 肥前洋一. 2016. 『[実験政治学](http://amzn.asia/d/8ocpEyn)』勁草書房.
   * Blais, Andre, Jean-Francois Laslier, and Karine Van der Straeten Ed. 2016. [*Voting Experiments.*](http://amzn.asia/d/gXuYoBa) Springer.
* R Packages for Data Analysis
   * {[tidyverse](https://cran.r-project.org/web/packages/tidyverse/index.html)}: Easily Install and Load the 'Tidyverse'.
      * {tidyverse}パッケージは{dplyr}、{ggplot2}、{haven}、{magrittr}、{purrr}、{readr}、{stringr}、{tibble}、{tidyr}などを含むパッケージ**群**である。

### マッチングとその応用

* Textbook
   * Rosenbaum. Paul R. 2002. [*Observational Studies, 2nd Ed.*](http://amzn.asia/d/hKI3pF1) Springer.
   * 星野崇宏. 2009.『[調査観察データの統計科学―因果推論・選択バイアス・データ融合―](http://amzn.asia/d/dIlcuiG)』岩波書店（第2・3・4章）
* Article
   * Rosenbaum, Paul R., and Donald B. Rubin. 1983. "[The Central Role of the Propensity Score in Observational Studies for Causal Effects.](https://academic.oup.com/biomet/article/70/1/41/240879)" *Biometrika,* 70 (1): 41-55.
   * Abadie, Alberto and Javier Gardeazabal. 2003. "[The Economic Costs of Conflict: A Case Study of the Basque Country.](https://www.aeaweb.org/articles?id=10.1257/000282803321455188)" *American Economic Review.* 93(1): 113-132.
   * Morgan, Stephen L., and David J. Harding. 2006. "[Matching Estimators of Causal Effects: Prospects and Pitfalls in Theory and Practice.](http://journals.sagepub.com/doi/abs/10.1177/0049124106289164)" *Sociological Methods & Research,* 35(1): 3-60.
   * Ho, Daniel E., Kosuke Imai, Gary King, and Elizabeth A. Stuart. 2007. "[Matching as Nonparametric Preprocessing for Reducing Model Dependence in Parametric Causal Inference.](https://www.cambridge.org/core/journals/political-analysis/article/div-classtitlematching-as-nonparametric-preprocessing-for-reducing-model-dependence-in-parametric-causal-inferencediv/4D7E6D07C9727F5A604E5C9FCCA2DD21)" *Political Analysis,* 15: 199-236.
   * Sekhon, Jasjeet S. 2008. "[The Neyman-Rubin Model of Causal Inference and Estimation via Matching Methods.](http://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780199286546.001.0001/oxfordhb-9780199286546-e-11)" In Janet M. Box-Steffensmeier, Henry E. Brady, and David Collier, eds. *The Oxford Handbook of Political Methodology,* New York: Oxford University Press, Ch.11.
   * Stuart, Elizabeth A., and Donald B. Rubin. 2008. "[Best Practice in Quasi-Experimental Designs: Matching Methods for Causal Inference.](https://www.corwin.com/sites/default/files/upm-binaries/18066_Chapter_11.pdf)" In Jason W. Osborne, ed. *Best Practices in Quantitative Methods,* Thousand Oaks: Sage, Ch.11.
   * Sekhon, Jasjeet S. 2009. "[Opiates for the Matches: Matching Methods for Causal Inference.](https://www.annualreviews.org/doi/abs/10.1146/annurev.polisci.11.060606.135444)" *Annual Review of Political Science,* 12: 487-508.
   * Abadie, Alberto,Alexis Diamond, and Jens Hainmueller. 2010. "[Synthetic Control Methods for Comparative Case Studies: Estimating the Effect of California’s Tobacco Control Program.](https://www.tandfonline.com/doi/abs/10.1198/jasa.2009.ap08746)" *Journal of the American Statistical Association*. 105 (490): 493-505.
   * Stuart, Elizabeth A. 2010. "[Matching Methods for Causal Inference: A Review and a Look Forward.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2943670/)" *Statistical Science,* 25(1): 1-21.
   * Iacus, Stefano M., Gary King, and Giuseppe Porro. 2012. "[Causal Inference without Balance Checking: Coarsened Exact Matching.](https://www.cambridge.org/core/journals/political-analysis/article/causal-inference-without-balance-checking-coarsened-exact-matching/5ABCF5B3FC3089A87FD59CECBB3465C0)" *Political Analysis,* 20: 1-24.
   * Abadie, Alberto, Alexis Diamond, and Jens Hainmueller. 2014. "[Comparative Politics and the Synthetic Control Method.](https://onlinelibrary.wiley.com/doi/full/10.1111/ajps.12116)" *American Journal of Political Science.* 59 (2): 495-510.
   * Brodersen, Kay H., Fabian Gallusser, Jim Koehler, Nicolas Remy, and Steven L. Scott. 2015. "[Inferring causal impact using Bayesian structural time-series models.](https://research.google/pubs/pub41854/)" *Annals of Applied Statistics.* 9(1): 247-274.
   * 登藤直弥・小林哲郎・稲増一憲. 2016.「[ソフトニュースへの接触は政治的関心を高めるか―一般化傾向スコアを用いた因果推論―](https://doi.org/10.2333/jbhmk.43.129)」『行動計量学』43 (2): 129-141.
   * Samii, Cyrus, Laura Paler, and Sarah Zukerman Daly. 2017. "[Retrospective Causal Inference with Machine Learning Ensembles: An Application to Anti-recidivism Policies in Colombia.](https://www.cambridge.org/core/journals/political-analysis/article/retrospective-causal-inference-with-machine-learning-ensembles-an-application-to-antirecidivism-policies-in-colombia/B27477770599A4CE0ACB9204685EA95B)" *Political Analysis,* 24 (4): 434-456.
* R Package
   * {[Matching](https://cran.r-project.org/web/packages/Matching/index.html)}: Multivariate and Propensity Score Matching with Balance Optimization
   * {[MatchIt](https://cran.r-project.org/web/packages/MatchIt/index.html)}: Nonparametric Preprocessing for Parametric Causal Inference
   * {[WeightIt](https://cran.r-project.org/web/packages/WeightIt/index.html)}: Weighting for Covariate Balance in Observational Studies
   * {[SuperLearner](https://cran.r-project.org/web/packages/SuperLearner/index.html)}: Super Learner Prediction

### 差分の差分法

* Article
   * Card, David, and Alan B. Krueger. 1994. "[Minimum Wages and Employment: A Case Study of the Fast Food Industry in New Jersey and Pennsylvania.](https://www.aeaweb.org/articles?id=10.1257/aer.90.5.1397)" *American Economic Review,* 90 (5): 1397-1420.
   * Bertrand, Marianne, Esther Duflo, and Sendhil Mullainathan. 2004. "[How Much Should We Trust Differences-In-Differences Estimates?](https://academic.oup.com/qje/article/119/1/249/1876068)" *Quarterly Journal of Economics,* 119(1): 249-275.
   * Di Tella, Rafael, and Ernesto Schargrodsky. 2004. "[Do Police Reduce Crime? Estimates Using the Allocation of Police Forces After a Terrorist Attack.](https://www.aeaweb.org/articles?id=10.1257/000282804322970733)" *American Economic Review,* 94 (1): 115-133.
   * Abadie, Alberto. 2005. "[Semiparametric Difference-in-Differences Estimators.](https://www.jstor.org/stable/3700681)" *Review of Economic Studies,* 72(1): 1-19.
   * Lyall, Jason. 2009. "[Does Indiscriminate Violence Incite Insurgent Attacks? Evidence from Chechnya.](http://journals.sagepub.com/doi/10.1177/0022002708330881)" *Journal of Conflict Resolution,* 53(3): 331-362.
   * Lechner, Michael. 2010. "[The Estimation of Causal Effects by Difference-in-Difference Methods.](http://michael-lechner.eu/ml_pdf/journals/2011_Lechner_DiD_2011_ECO%200403%20Lechner_darf%20aufs%20Netz.pdf)" Working paper.
   * Asai, Yukiko, Ryo Kamibayashi, and Shintaro Yamaguchi. 2015. "[Childcare availability, household structure, and maternal employment.](https://www.sciencedirect.com/science/article/pii/S088915831500043X)" *Journal of the Japanese and International Economies,* 38: 172-192.
   * Fouirnaies, Alexander, and Hande Mutlu-Eren. 2015. "[English Bacon: Copartisan Bias in Intergovernmental Grant Allocation in England.](https://www.journals.uchicago.edu/doi/abs/10.1086/681563)" *Journal of Politics,* 77(3): 805--817.
   * Xu, Yiqing. 2017. "[Generalized Synthetic Control Method: Causal Inference with Interactive Fixed Effects Models,](https://doi.org/10.1017/pan.2016.2.)" *Political Analysis,* 25(1): 56-76.
* R Packages
   * {[estimatr](https://cran.r-project.org/web/packages/estimatr/index.html)}: Fast Estimators for Design-Based Inference
   * {[CausalImpact](https://cran.r-project.org/web/packages/CausalImpact/index.html)}: Inferring Causal Effects using Bayesian Structural Time-Series Models
   * {[Synth](https://cran.r-project.org/web/packages/Synth/index.html)}: Synthetic Control Group Method for Comparative Case Studies
   * {[gsynth](https://cran.r-project.org/web/packages/gsynth/index.html)}: Generalized Synthetic Control Method

### 回帰不連続デザイン

	\begin{itemize}
		\item Textbook
		\begin{enumerate}
			\item AP (2008): Ch.6
			\item AP (2014): Ch.4
			\item 森田 (2014): 第22章
			\item 星野・田中 (2016): 第10章
			\item 中村・津川 (2017): 第6章
			\item 伊藤 (2017): 第3章
			\item 安井 (2020): 第5章
			\item \href{https://www.amazon.co.jp/dp/1108710204}{Cattaneo, Matias D.. 2020. \emph{A Practical Introduction to Regression Discontinuity Designs,} ‎ Cambridge University Press.}
		\end{enumerate}
		\item Article
		\begin{enumerate}
			\item \href{https://obsstudies.org/reprint-regression-discontinuity-analysis-an-alternative-to-the-ex-post-facto-experiment/}{Thistlethwaite, Donald L., and Donald T. Campbell. 1960. "Regression-discontinuity analysis: An alternative to the ex post facto experiment." \emph{Journal of Educational Psychology,} 51(6): 309--317.}
			\item \href{https://www.jstor.org/stable/2692190}{Hahn, Jinyong, Petra Todd, and Wilbert Van der Klaauw. 2001. "Identification and Estimation of Treatment Effects with a Regression-Discontinuity Design." \emph{Econometrica,} 69 (1): 201--209.}
			\item \href{http://econ.ucsb.edu/~doug/245a/Papers/Estimation%20in%20RD%20Model.pdf}{Poter, Jack. 2003. "Estimation in the Regression Discontinuity Model." Working Paper.}
			\item \href{https://www.sciencedirect.com/science/article/pii/S0304407607001091}{Imbens, Guido W., and Thomas Lemieux. 2008. "Regression Discontinuity Designs: A Guide to Practice." \emph{Journal of Econometrics,} 142 (2): 615--635.}
			\item \href{https://www.sciencedirect.com/science/article/pii/S0304407607001121}{Lee, David S.. 2008. "Randomized experiments from non-random selection in U.S. House elections." \emph{Journal of Econometrics,} 142 (2): 675--697.}
			\item \href{https://www.sciencedirect.com/science/article/pii/S0304407607001133}{Justin McCrary. 2008. "Manipulation of the running variable in the regression discontinuity design: A density test." \emph{Journal of Econometrics,} 142 (2): 698-714.}
			\item \href{https://www.aeaweb.org/articles?id=10.1257/jel.48.2.281}{Lee, David S., and Thomas Lemieux. 2010. "Regression Discontinuity Designs in Economics." \emph{Journal of Economic Literature}, 48 (2): 281--355.}
			\item \href{https://www.aeaweb.org/articles?id=10.1257/jel.48.2.281}{Lee, David S., and Thomas Lemieux. 2010. "Regression Discontinuity Designs in Economics." \emph{Journal of Economic Literature,} 48 (2): 281--355.}
			\item \href{https://academic.oup.com/restud/article/79/3/933/1533189}{Imbens, Guido, and Karthik Kalyanaraman. 2011. "Optimal Bandwidth Choice for the Regression Discontinuity Estimator." \emph{Review of Economic Studies,} 79 (3): 933--959.}
			\item \href{https://www.sciencedirect.com/science/article/pii/S0261379416301020}{Ariga, Kenichi, Yusaku Horiuchi, Roland Mansilla, and Michio Umeda. 2016. "No sorting, no advantage: Regression discontinuity estimates of incumbency advantage in Japan." \emph{Electoral Studies,} 43: 21--31.}
			\item \href{https://www.tandfonline.com/doi/full/10.1080/07350015.2017.1366909}{Andrew Gelman and Guido Imbens. 2019. "Why High-Order Polynomials Should Not Be Used in Regression Discontinuity Designs," \emph{Journal of Business & Economic Statistics,} 37(3): 447-456.}
		\end{enumerate}
		\item Monograph
		\begin{enumerate}
			\item \href{https://sites.google.com/site/rdpackages/replication/cit-2018-cup}{Cattaneo, Matias D., Nicol\'as Idrobo and Roc\'io Titiunik. 2018. \emph{A Practical Introduction to Regression Discontinuity Designs: Volume I.} Cambridge University Press.}
			\item \href{https://sites.google.com/site/rdpackages/replication/cit-2018-cup}{Cattaneo, Matias D., Nicol\'as Idrobo and Roc\'io Titiunik. 2018. \emph{A Practical Introduction to Regression Discontinuity Designs: Volume II.} Cambridge University Press.}
		\end{enumerate}
		\item R package
		\begin{enumerate}
			\item \href{https://cran.r-project.org/web/packages/rdd/index.html}{\{rdd\}: Regression Discontinuity Estimation}
			\item \href{https://cran.r-project.org/web/packages/rddtools/index.html}{\{rddtools\}: Toolbox for Regression Discontinuity Design ('RDD')}
			\item \href{https://cran.r-project.org/web/packages/rddapp/index.html}{\{rddapp\}: Regression Discontinuity Design Application}
			\item \href{https://cran.r-project.org/web/packages/rdrobust/index.html}{\{rdrobust\}: Robust Data-Driven Statistical Inference in Regression-Discontinuity Designs}
			\item \href{https://cran.r-project.org/web/packages/rdmulti/index.html}{\{rdmulti\}: Analysis of RD Designs with Multiple Cutoffs or Scores}
			\item \href{https://cran.r-project.org/web/packages/rdpower/index.html}{\{rdpower\}: Power Calculations for RD Designs}
		\end{enumerate}
	\end{itemize}

### 操作変数法

	以下の内容はLab Sessionが行わない場合のみ、解説する。

	\begin{itemize}
		\item Textbook
		\begin{enumerate}
			\item AP (2008): Ch.4
			\item AP (2014): Ch.3
			\item 森田 (2014): 第20$\cdot$21章
			\item 星野・田中 (2016): 第11章
			\item 中村・津川 (2017): 第5章
		\end{enumerate}
		\item Article
		\begin{enumerate}
			\item \href{https://www.aeaweb.org/articles?id=10.1257/jep.15.4.69}{Angrist, Joshua D. and Alan B. Krueger. 2001. "Instrumental Variables and the Search for Identification: From Supply and Demand to Natural Experiments," \emph{Journal of Economic Perspectives,} 15 (4): 69--85}
			\item \href{https://www.cambridge.org/core/journals/political-analysis/article/model-specification-in-instrumentalvariables-regression/793976A184DB66ACFC0013034B703294}{Dunning, Thad. 2008. "Model Specification in Instrumental-Variables Regression." \emph{Political Analysis,} 16 (3): 290--302.}
			\item \href{https://www.cambridge.org/core/journals/political-analysis/article/opium-for-the-masses-how-foreign-media-can-stabilize-authoritarian-regimes/CE2EAEB87BD8DAF009BE4BBA6C30A0F8}{Kern, Holger Lutz and Jens Hainmueller. 2009. "Opium for the Masses: How Foreign Media Can Stabilize Authoritarian Regimes." \emph{Political Analysis,} 17 (4): 377--399.}
			\item \href{https://doi.org/10.1111/j.1540-5907.2010.00477.x}{Allison J. Sovey and Donald P. Green. 2010. "Instrumental Variables Estimation in Political Science: A Readers’ Guide," \emph{American Journal of Political Science,} 55(1): 188-200.}
			\item \href{https://doi.org/10.1146/annurev-soc-081309-150141}{Bollen, Kenneth A.. 2012. "Instrumental Variables in Sociology and the Social Sciences," \emph{Annual Review of Sociology,} 38:37--72.}
			\item \href{https://www.cambridge.org/core/journals/political-analysis/article/beyond-late-estimation-of-the-average-treatment-effect-with-an-instrumental-variable/604E0803793175CF88329DB34DAA80B3}{Aronow, Peter M. and Allison Carnegie. 2013. "Beyond LATE: Estimation of the Average Treatment Effect with an Instrumental Variable." \emph{Political Analysis,} 21 (4): 492--506.}
		\end{enumerate}
		\item R package
		\begin{enumerate}
			\item \href{https://cran.r-project.org/web/packages/AER/index.html}{\{AER\}: Applied Econometrics with R}
			\item \href{https://cran.r-project.org/web/packages/ivreg/index.html}{\{ivreg\}: Instrumental-Variables Regression by '2SLS', '2SM', or '2SMM', with Diagnostics}
		\end{enumerate}
	\end{itemize}