<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Causal Inference@Kobe - 差分の差分法</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../material/rdd.html" rel="next">
<link href="../material/matching.html" rel="prev">
<link href="../figs/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-9F94XL4N4M"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-9F94XL4N4M', { 'anonymize_ip': true});
</script>

<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../index.html">
    <img src="../figs/logo.png" alt="">
    <span class="navbar-title">Causal Inference@Kobe</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html">シラバス</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-rの使い方" role="button" data-bs-toggle="dropdown" aria-expanded="false">Rの使い方</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-rの使い方">    
        <li>
    <a class="dropdown-item" href="../intro/install.html">
 <span class="dropdown-text">Rの導入</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../intro/rstudio.html">
 <span class="dropdown-text">RStudioの設定</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../intro/project.html">
 <span class="dropdown-text">プロジェクト管理</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../intro/file.html">
 <span class="dropdown-text">ファイル管理</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../intro/filesystem.html">
 <span class="dropdown-text">ファイル管理術</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../intro/packages.html">
 <span class="dropdown-text">パッケージ</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-" role="button" data-bs-toggle="dropdown" aria-expanded="false">講義資料</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-">    
        <li>
    <a class="dropdown-item" href="../material/intro_rct.html">
 <span class="dropdown-text">因果推論の考え方とランダム化比較試験</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../material/matching.html">
 <span class="dropdown-text">マッチング</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../material/did.html">
 <span class="dropdown-text">差分の差分法</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../material/rdd.html">
 <span class="dropdown-text">回帰不連続デザイン</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../material/iv.html">
 <span class="dropdown-text">操作変数法</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../data.html">データ集</a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://jupyter.cs.rcos.nii.ac.jp/"><i class="bi bi-terminal" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.jaysong.net/RBook/"><i class="bi bi-book" role="img">
</i> 
 </a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">差分の差分法</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/intro_rct.html" class="sidebar-item-text sidebar-link">因果推論の考え方とランダム化比較試験</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/matching.html" class="sidebar-item-text sidebar-link">マッチング</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/did.html" class="sidebar-item-text sidebar-link active">差分の差分法</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/rdd.html" class="sidebar-item-text sidebar-link">回帰不連続デザイン</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/iv.html" class="sidebar-item-text sidebar-link">操作変数法</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">目次</h2>
   
  <ul>
  <li><a href="#スライド" id="toc-スライド" class="nav-link active" data-scroll-target="#スライド">スライド</a></li>
  <li><a href="#セットアップ" id="toc-セットアップ" class="nav-link" data-scroll-target="#セットアップ">セットアップ</a></li>
  <li><a href="#diff-in-diff" id="toc-diff-in-diff" class="nav-link" data-scroll-target="#diff-in-diff">Diff-in-Diff</a></li>
  <li><a href="#scm" id="toc-scm" class="nav-link" data-scroll-target="#scm">SCM</a></li>
  <li><a href="#causalimpact" id="toc-causalimpact" class="nav-link" data-scroll-target="#causalimpact">CausalImpact</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">差分の差分法</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="スライド" class="level2">
<h2 class="anchored" data-anchor-id="スライド">スライド</h2>
<p><a href="../slide/did.html" class="btn btn-primary btn-sm" target="_blank" role="button"><i class="bi bi-window"></i> 新しいタブで開く</a></p>
<iframe class="slide-deck" src="../slide/did.html" width="100%" style="aspect-ratio: 16 / 9.2;"></iframe>
</section>
<section id="セットアップ" class="level2">
<h2 class="anchored" data-anchor-id="セットアップ">セットアップ</h2>
<p>　本日の実習に必要なパッケージとデータを読み込む。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse,     <span class="co"># Rの必須パッケージ</span></span>
<span id="cb1-2"><a href="#cb1-2"></a>               summarytools,  <span class="co"># 記述統計</span></span>
<span id="cb1-3"><a href="#cb1-3"></a>               modelsummary,  <span class="co"># 推定結果の要約</span></span>
<span id="cb1-4"><a href="#cb1-4"></a>               estimatr,      <span class="co"># ロバストな回帰分析</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>               gsynth,        <span class="co"># 一般化SCM</span></span>
<span id="cb1-6"><a href="#cb1-6"></a>               panelView,     <span class="co"># パネルデータのチェック</span></span>
<span id="cb1-7"><a href="#cb1-7"></a>               CausalImpact)  <span class="co"># CausalImpactの実装</span></span>
<span id="cb1-8"><a href="#cb1-8"></a></span>
<span id="cb1-9"><a href="#cb1-9"></a>did_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/did_data5.csv"</span>)</span>
<span id="cb1-10"><a href="#cb1-10"></a></span>
<span id="cb1-11"><a href="#cb1-11"></a>did_df</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18,749 × 14
   county state  year shooting fatal_s…¹ non_f…² turnout demvote popul…³ non_w…⁴
    &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1   1001 01     1996        0         0       0    56.1    32.5   40207   0.190
 2   1001 01     2000        0         0       0    56.8    28.7   44021   0.189
 3   1001 01     2004        0         0       0    60.2    23.7   48366   0.196
 4   1001 01     2008        0         0       0    64.1    25.8   53277   0.205
 5   1001 01     2012        0         0       0    61.0    26.5   55027   0.212
 6   1001 01     2016        0         0       0    60.7    24.0   55416   0.228
 7   1003 01     1996        0         0       0    51.8    27.1  125412   0.123
 8   1003 01     2000        0         0       0    54.6    24.8  141342   0.122
 9   1003 01     2004        0         0       0    59.8    22.5  156266   0.122
10   1003 01     2008        0         0       0    62.4    23.8  175827   0.122
# … with 18,739 more rows, 4 more variables: change_unem_rate &lt;dbl&gt;,
#   county_f &lt;dbl&gt;, state_f &lt;chr&gt;, year_f &lt;dbl&gt;, and abbreviated variable names
#   ¹​fatal_shooting, ²​non_fatal_shooting, ³​population, ⁴​non_white
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</code></pre>
</div>
</div>
<p>　データの詳細はスライドを参照すること。DID推定には時間（年）とカウンティー（郡）の固定効果を投入し、州レベルでクラスタリングした標準誤差を使う予定である。これらの変数を予めfactor化しておこう。factor化した変数は変数名の後ろに<code>_f</code>を付けて、新しい列として追加しておく。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>did_df <span class="ot">&lt;-</span> did_df <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>  <span class="fu">mutate</span>(<span class="at">county_f =</span> <span class="fu">factor</span>(county),</span>
<span id="cb3-3"><a href="#cb3-3"></a>         <span class="at">state_f  =</span> <span class="fu">factor</span>(state),</span>
<span id="cb3-4"><a href="#cb3-4"></a>         <span class="at">year_f   =</span> <span class="fu">factor</span>(year))</span>
<span id="cb3-5"><a href="#cb3-5"></a></span>
<span id="cb3-6"><a href="#cb3-6"></a>did_df</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18,749 × 14
   county state  year shooting fatal_s…¹ non_f…² turnout demvote popul…³ non_w…⁴
    &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1   1001 01     1996        0         0       0    56.1    32.5   40207   0.190
 2   1001 01     2000        0         0       0    56.8    28.7   44021   0.189
 3   1001 01     2004        0         0       0    60.2    23.7   48366   0.196
 4   1001 01     2008        0         0       0    64.1    25.8   53277   0.205
 5   1001 01     2012        0         0       0    61.0    26.5   55027   0.212
 6   1001 01     2016        0         0       0    60.7    24.0   55416   0.228
 7   1003 01     1996        0         0       0    51.8    27.1  125412   0.123
 8   1003 01     2000        0         0       0    54.6    24.8  141342   0.122
 9   1003 01     2004        0         0       0    59.8    22.5  156266   0.122
10   1003 01     2008        0         0       0    62.4    23.8  175827   0.122
# … with 18,739 more rows, 4 more variables: change_unem_rate &lt;dbl&gt;,
#   county_f &lt;fct&gt;, state_f &lt;fct&gt;, year_f &lt;fct&gt;, and abbreviated variable names
#   ¹​fatal_shooting, ²​non_fatal_shooting, ³​population, ⁴​non_white
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</code></pre>
</div>
</div>
<p>　連続変数（<code>shooting</code>から<code>change_unem_rate</code>まで）の記述統計量を出力する。ここで一つ注意が必要だ。それは<code>select()</code>関数の使い方である。具体的に言えば、使い方そのものは変わらない。問題は、現在、<code>select()</code>関数が2つ以上存在するという点だ。最初に読み込んだ{gsynth}パッケージは{MASS}パッケージにも依存しているため、自動的に{MASS}も読み込まれる。この{MASS}にも<code>select()</code>関数が存在する。しかも、{gsynth}は{tidyverse}よりも先に読み込まれているので、<code>select()</code>のみ書くと、{MASS}の<code>select()</code>関数として認識する。したがって、「どのパッケージの<code>select()</code>関数か」を具体的に書く必要がある。書き方は<code>パッケージ名::関数名()</code>だ。{tidyverse}内には{dplyr}というパッケージがあり、列の抽出に使う<code>select()</code>関数はこの{dplyr}が提供しているため、<code>dplyr::select()</code>と書く必要がある。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>did_df <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(shooting<span class="sc">:</span>change_unem_rate) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3"></a>  <span class="fu">descr</span>(<span class="at">stats =</span> <span class="fu">c</span>(<span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"min"</span>, <span class="st">"max"</span>, <span class="st">"n.valid"</span>),</span>
<span id="cb5-4"><a href="#cb5-4"></a>        <span class="at">transpose =</span> <span class="cn">TRUE</span>, <span class="at">order =</span> <span class="st">"p"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Error : Can't find dplyr</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Descriptive Statistics  

                               Mean     Std.Dev      Min           Max    N.Valid
------------------------ ---------- ----------- -------- ------------- ----------
                shooting       0.00        0.07     0.00          1.00   18749.00
          fatal_shooting       0.00        0.05     0.00          1.00   18749.00
      non_fatal_shooting       0.00        0.04     0.00          1.00   18749.00
                 turnout      57.94       10.32     1.08        300.00   18627.00
                 demvote      39.01       13.79     3.14         92.85   18627.00
              population   95121.69   306688.63    55.00   10137915.00   18749.00
               non_white       0.13        0.16     0.00          0.96   18749.00
        change_unem_rate      -0.39        2.34   -19.60         15.30   18749.00</code></pre>
</div>
</div>
</section>
<section id="diff-in-diff" class="level2">
<h2 class="anchored" data-anchor-id="diff-in-diff">Diff-in-Diff</h2>
<p>　それでは差分の差分法の実装について紹介する。推定式は以下の通りである。</p>
<p><span class="math display">\[
\mbox{Outcome}_{i, t} = \beta_0 + \beta_1 \mbox{Shooting}_{i, t} + \sum_k \delta_{k, i, t} \mbox{Controls}_{k, i, t} + \lambda_{t} + \omega_{i} + \varepsilon_{i, t}
\]</span></p>
<ul>
<li><span class="math inline">\(\mbox{Otucome}\)</span>: 応答変数
<ul>
<li><code>turnout</code>: 投票率（大統領選挙）</li>
<li><code>demvote</code>: 民主党候補者の得票率</li>
</ul></li>
<li><span class="math inline">\(\mbox{Shooting}\)</span>: 処置変数
<ul>
<li><code>shooting</code>: 銃撃事件の発生有無</li>
<li><code>fatal_shooting</code>: 死者を伴う銃撃事件の発生有無</li>
<li><code>non_fatal_shooting</code>: 死者を伴わない銃撃事件の発生有無</li>
</ul></li>
<li><span class="math inline">\(\mbox{Controls}\)</span>: 統制変数
<ul>
<li><code>population</code>: カウンティーの人口</li>
<li><code>non_white</code>: 非白人の割合</li>
<li><code>change_unem_rate</code>: 失業率の変化</li>
<li>統制変数あり/なしのモデルを個別に推定</li>
</ul></li>
<li><span class="math inline">\(\lambda\)</span>: 年固定効果</li>
<li><span class="math inline">\(\omega\)</span>: カウンティー固定効果</li>
</ul>
<p>応答変数が2種類、処置変数が3種類、共変量の有無でモデルを分けるので、推定するモデルは計12個である。</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">モデル</th>
<th style="text-align: left;">オブジェクト名</th>
<th style="text-align: left;">応答変数</th>
<th style="text-align: left;">処置変数</th>
<th style="text-align: left;">統制変数</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">モデル1</td>
<td style="text-align: left;"><code>did_fit1</code></td>
<td style="text-align: left;"><code>turnout</code></td>
<td style="text-align: left;"><code>shooting</code></td>
<td style="text-align: left;">なし</td>
</tr>
<tr class="even">
<td style="text-align: left;">モデル2</td>
<td style="text-align: left;"><code>did_fit2</code></td>
<td style="text-align: left;"><code>turnout</code></td>
<td style="text-align: left;"><code>shooting</code></td>
<td style="text-align: left;">あり</td>
</tr>
<tr class="odd">
<td style="text-align: left;">モデル3</td>
<td style="text-align: left;"><code>did_fit3</code></td>
<td style="text-align: left;"><code>turnout</code></td>
<td style="text-align: left;"><code>fatal_shooting</code></td>
<td style="text-align: left;">なし</td>
</tr>
<tr class="even">
<td style="text-align: left;">モデル4</td>
<td style="text-align: left;"><code>did_fit4</code></td>
<td style="text-align: left;"><code>turnout</code></td>
<td style="text-align: left;"><code>fatal_shooting</code></td>
<td style="text-align: left;">あり</td>
</tr>
<tr class="odd">
<td style="text-align: left;">モデル5</td>
<td style="text-align: left;"><code>did_fit5</code></td>
<td style="text-align: left;"><code>turnout</code></td>
<td style="text-align: left;"><code>non_fatal_shooting</code></td>
<td style="text-align: left;">なし</td>
</tr>
<tr class="even">
<td style="text-align: left;">モデル6</td>
<td style="text-align: left;"><code>did_fit6</code></td>
<td style="text-align: left;"><code>turnout</code></td>
<td style="text-align: left;"><code>non_fatal_shooting</code></td>
<td style="text-align: left;">あり</td>
</tr>
<tr class="odd">
<td style="text-align: left;">モデル7</td>
<td style="text-align: left;"><code>did_fit7</code></td>
<td style="text-align: left;"><code>demvote</code></td>
<td style="text-align: left;"><code>shooting</code></td>
<td style="text-align: left;">なし</td>
</tr>
<tr class="even">
<td style="text-align: left;">モデル8</td>
<td style="text-align: left;"><code>did_fit8</code></td>
<td style="text-align: left;"><code>demvote</code></td>
<td style="text-align: left;"><code>shooting</code></td>
<td style="text-align: left;">あり</td>
</tr>
<tr class="odd">
<td style="text-align: left;">モデル9</td>
<td style="text-align: left;"><code>did_fit9</code></td>
<td style="text-align: left;"><code>demvote</code></td>
<td style="text-align: left;"><code>fatal_shooting</code></td>
<td style="text-align: left;">なし</td>
</tr>
<tr class="even">
<td style="text-align: left;">モデル10</td>
<td style="text-align: left;"><code>did_fit10</code></td>
<td style="text-align: left;"><code>demvote</code></td>
<td style="text-align: left;"><code>fatal_shooting</code></td>
<td style="text-align: left;">あり</td>
</tr>
<tr class="odd">
<td style="text-align: left;">モデル11</td>
<td style="text-align: left;"><code>did_fit11</code></td>
<td style="text-align: left;"><code>demvote</code></td>
<td style="text-align: left;"><code>non_fatal_shooting</code></td>
<td style="text-align: left;">なし</td>
</tr>
<tr class="even">
<td style="text-align: left;">モデル12</td>
<td style="text-align: left;"><code>did_fit12</code></td>
<td style="text-align: left;"><code>demvote</code></td>
<td style="text-align: left;"><code>non_fatal_shooting</code></td>
<td style="text-align: left;">あり</td>
</tr>
</tbody>
</table>
<p>　まずはモデル1を推定し、<code>did_fit1</code>という名のオブジェクトとして格納する。基本的には線形回帰分析であるため、<code>lm()</code>でも推定はできる。しかし、差分の差分法の場合、通常、クラスター化した頑健な標準誤差（cluster robust standard error）を使う。<code>lm()</code>単体ではこれが計算できないため、今回は{estimatr}パッケージが提供する<code>lm_robust()</code>関数を使用する。使い方は<code>lm()</code>同様、まず回帰式と使用するデータ名を指定する。続いて、固定効果を<code>fixed_effects</code>引数で指定する<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>。書き方は<code>~固定効果変数1 + 固定効果変数2 + ...</code>である。回帰式と違って、<code>~</code>の左側には変数がないことに注意すること。続いて、<code>clusters</code>引数でクラスタリングする変数を指定する。今回は州レベルでクラスタリングするので、<code>state_f</code>で良い。最後に標準誤差のタイプを指定するが、デフォルトは<code>"CR2"</code>となっている。今回のデータはそれなりの大きさのデータであり、<code>"CR2"</code>だと推定時間が非常に長くなる。ここでは推定時間が比較的早い<code>"stata"</code>とする。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>did_fit1 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(turnout <span class="sc">~</span> shooting, </span>
<span id="cb8-2"><a href="#cb8-2"></a>                      <span class="at">data          =</span> did_df, </span>
<span id="cb8-3"><a href="#cb8-3"></a>                      <span class="at">fixed_effects =</span> <span class="sc">~</span>year_f <span class="sc">+</span> county_f,</span>
<span id="cb8-4"><a href="#cb8-4"></a>                      <span class="at">clusters      =</span> state_f,</span>
<span id="cb8-5"><a href="#cb8-5"></a>                      <span class="at">se_type       =</span> <span class="st">"stata"</span>)</span>
<span id="cb8-6"><a href="#cb8-6"></a></span>
<span id="cb8-7"><a href="#cb8-7"></a><span class="fu">summary</span>(did_fit1)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm_robust(formula = turnout ~ shooting, data = did_df, clusters = state_f, 
    fixed_effects = ~year_f + county_f, se_type = "stata")

Standard error type:  stata 

Coefficients:
         Estimate Std. Error t value Pr(&gt;|t|) CI Lower CI Upper DF
shooting  -0.5211     0.6457  -0.807   0.4235   -1.819   0.7764 49

Multiple R-squared:  0.8575 ,   Adjusted R-squared:  0.8288
Multiple R-squared (proj. model):  6.907e-05 ,  Adjusted R-squared (proj. model):  -0.2008 
F-statistic (proj. model): 0.6513 on 1 and 49 DF,  p-value: 0.4235</code></pre>
</div>
</div>
<p>　処置効果の推定値は-0.521である。これは学校内銃撃事件が発生したカウンティーの場合、大統領選挙において投票率が約-0.521%p低下することを意味する。しかし、標準誤差がかなり大きく、統計的有意な結果ではない。つまり、「学校内銃撃事件が投票率を上げる（or 下げる）とは言えない」と解釈できる。決して「学校内銃撃事件が投票率を上げない（or 下げない）」と解釈しないこと。</p>
<p>　共変量を投入してみたらどうだろうか。たとえば、人口は自治体の都市化程度を表すこともあるので、都市化程度と投票率には関係があると考えられる。また、人口が多いと自然に事件が発生する確率もあがるので、交絡要因として考えられる。人種や失業率も同様であろう。ここではカウンティーの人口（<code>population</code>）、非白人の割合（<code>non_white</code>）、失業率の変化（<code>change_unem_rate</code>）を統制変数として投入し、<code>did_fit2</code>という名で格納する。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>did_fit2 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(turnout <span class="sc">~</span> shooting <span class="sc">+</span> </span>
<span id="cb10-2"><a href="#cb10-2"></a>                        population <span class="sc">+</span> non_white <span class="sc">+</span> change_unem_rate, </span>
<span id="cb10-3"><a href="#cb10-3"></a>                      <span class="at">data          =</span> did_df, </span>
<span id="cb10-4"><a href="#cb10-4"></a>                      <span class="at">fixed_effects =</span> <span class="sc">~</span>year_f <span class="sc">+</span> county_f,</span>
<span id="cb10-5"><a href="#cb10-5"></a>                      <span class="at">clusters      =</span> state_f,</span>
<span id="cb10-6"><a href="#cb10-6"></a>                      <span class="at">se_type       =</span> <span class="st">"stata"</span>)</span>
<span id="cb10-7"><a href="#cb10-7"></a></span>
<span id="cb10-8"><a href="#cb10-8"></a><span class="fu">summary</span>(did_fit2)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm_robust(formula = turnout ~ shooting + population + non_white + 
    change_unem_rate, data = did_df, clusters = state_f, fixed_effects = ~year_f + 
    county_f, se_type = "stata")

Standard error type:  stata 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)   CI Lower   CI Upper
shooting         -7.098e-01  6.237e-01  -1.138  0.26066 -1.963e+00  5.436e-01
population        8.029e-06  5.688e-06   1.411  0.16443 -3.402e-06  1.946e-05
non_white        -3.483e+01  1.558e+01  -2.236  0.02990 -6.613e+01 -3.534e+00
change_unem_rate  1.592e-01  6.584e-02   2.418  0.01938  2.688e-02  2.915e-01
                 DF
shooting         49
population       49
non_white        49
change_unem_rate 49

Multiple R-squared:  0.8598 ,   Adjusted R-squared:  0.8316
Multiple R-squared (proj. model):  0.01669 ,    Adjusted R-squared (proj. model):  -0.1811 
F-statistic (proj. model): 5.047 on 4 and 49 DF,  p-value: 0.001739</code></pre>
</div>
</div>
<p>　処置効果の推定値は-0.710である。これは他の条件が同じ場合、学校内銃撃事件が発生したカウンティーは大統領選挙において投票率が約-0.710%p低下することを意味する。ちなみに、<code>e-01</code>は<span class="math inline">\(\times 10^{-1}\)</span>を、<code>e-06</code>は<span class="math inline">\(\times 10^{-6}\)</span>を、<code>e+01</code>は<span class="math inline">\(\times 10^{1}\)</span>意味する。今回も統計的に非有意な結果が得られている。</p>
<p>　これまでの処置変数は死者の有無と関係なく、学校内銃撃事件が発生したか否かだった。もしかしたら、死者を伴う銃撃事件が発生した場合、その効果が大きいかも知れない。したがって、これからは処置変数を死者を伴う学校内銃撃事件の発生有無（<code>fatal_shooting</code>）、死者を伴わない学校内銃撃事件の発生有無（<code>non_fatal_shooting</code>）に変えてもう一度推定してみよう。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>did_fit3 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(turnout <span class="sc">~</span> fatal_shooting, </span>
<span id="cb12-2"><a href="#cb12-2"></a>                      <span class="at">data          =</span> did_df, </span>
<span id="cb12-3"><a href="#cb12-3"></a>                      <span class="at">fixed_effects =</span> <span class="sc">~</span>year_f <span class="sc">+</span> county_f,</span>
<span id="cb12-4"><a href="#cb12-4"></a>                      <span class="at">clusters      =</span> state_f,</span>
<span id="cb12-5"><a href="#cb12-5"></a>                      <span class="at">se_type       =</span> <span class="st">"stata"</span>)</span>
<span id="cb12-6"><a href="#cb12-6"></a></span>
<span id="cb12-7"><a href="#cb12-7"></a>did_fit4 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(turnout <span class="sc">~</span> fatal_shooting <span class="sc">+</span> </span>
<span id="cb12-8"><a href="#cb12-8"></a>                        population <span class="sc">+</span> non_white <span class="sc">+</span> change_unem_rate, </span>
<span id="cb12-9"><a href="#cb12-9"></a>                      <span class="at">data          =</span> did_df, </span>
<span id="cb12-10"><a href="#cb12-10"></a>                      <span class="at">fixed_effects =</span> <span class="sc">~</span>year_f <span class="sc">+</span> county_f,</span>
<span id="cb12-11"><a href="#cb12-11"></a>                      <span class="at">clusters      =</span> state_f,</span>
<span id="cb12-12"><a href="#cb12-12"></a>                      <span class="at">se_type       =</span> <span class="st">"stata"</span>)</span>
<span id="cb12-13"><a href="#cb12-13"></a></span>
<span id="cb12-14"><a href="#cb12-14"></a>did_fit5 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(turnout <span class="sc">~</span> non_fatal_shooting, </span>
<span id="cb12-15"><a href="#cb12-15"></a>                      <span class="at">data          =</span> did_df, </span>
<span id="cb12-16"><a href="#cb12-16"></a>                      <span class="at">fixed_effects =</span> <span class="sc">~</span>year_f <span class="sc">+</span> county_f,</span>
<span id="cb12-17"><a href="#cb12-17"></a>                      <span class="at">clusters      =</span> state_f,</span>
<span id="cb12-18"><a href="#cb12-18"></a>                      <span class="at">se_type       =</span> <span class="st">"stata"</span>)</span>
<span id="cb12-19"><a href="#cb12-19"></a></span>
<span id="cb12-20"><a href="#cb12-20"></a>did_fit6 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(turnout <span class="sc">~</span> non_fatal_shooting <span class="sc">+</span> </span>
<span id="cb12-21"><a href="#cb12-21"></a>                        population <span class="sc">+</span> non_white <span class="sc">+</span> change_unem_rate, </span>
<span id="cb12-22"><a href="#cb12-22"></a>                      <span class="at">data          =</span> did_df, </span>
<span id="cb12-23"><a href="#cb12-23"></a>                      <span class="at">fixed_effects =</span> <span class="sc">~</span>year_f <span class="sc">+</span> county_f,</span>
<span id="cb12-24"><a href="#cb12-24"></a>                      <span class="at">clusters      =</span> state_f,</span>
<span id="cb12-25"><a href="#cb12-25"></a>                      <span class="at">se_type       =</span> <span class="st">"stata"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>　これまで推定してきた6つのモデルを比較してみよう。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="fu">modelsummary</span>(<span class="fu">list</span>(did_fit1, did_fit2, did_fit3, </span>
<span id="cb13-2"><a href="#cb13-2"></a>                  did_fit4, did_fit5, did_fit6))</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> Model 1 </th>
   <th style="text-align:center;"> Model 2 </th>
   <th style="text-align:center;"> Model 3 </th>
   <th style="text-align:center;"> Model 4 </th>
   <th style="text-align:center;"> Model 5 </th>
   <th style="text-align:center;"> Model 6 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> shooting </td>
   <td style="text-align:center;"> −0.521 </td>
   <td style="text-align:center;"> −0.710 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;"> (0.646) </td>
   <td style="text-align:center;"> (0.624) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> population </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.000 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.000 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.000 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (0.000) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (0.000) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (0.000) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> non_white </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> −34.834 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> −34.844 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> −34.814 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (15.575) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (15.618) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (15.614) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> change_unem_rate </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.159 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.159 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.160 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (0.066) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (0.066) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (0.066) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> fatal_shooting </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> −0.678 </td>
   <td style="text-align:center;"> −0.918 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (0.619) </td>
   <td style="text-align:center;"> (0.658) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> non_fatal_shooting </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> −0.239 </td>
   <td style="text-align:center;"> −0.327 </td>
  </tr>
  <tr>
   <td style="text-align:left;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px"> (1.094) </td>
   <td style="text-align:center;box-shadow: 0px 1px"> (1.145) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Num.Obs. </td>
   <td style="text-align:center;"> 18627 </td>
   <td style="text-align:center;"> 18627 </td>
   <td style="text-align:center;"> 18627 </td>
   <td style="text-align:center;"> 18627 </td>
   <td style="text-align:center;"> 18627 </td>
   <td style="text-align:center;"> 18627 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> R2 </td>
   <td style="text-align:center;"> 0.857 </td>
   <td style="text-align:center;"> 0.860 </td>
   <td style="text-align:center;"> 0.857 </td>
   <td style="text-align:center;"> 0.860 </td>
   <td style="text-align:center;"> 0.857 </td>
   <td style="text-align:center;"> 0.860 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> AIC </td>
   <td style="text-align:center;"> 103543.4 </td>
   <td style="text-align:center;"> 103237.2 </td>
   <td style="text-align:center;"> 103543.3 </td>
   <td style="text-align:center;"> 103237.1 </td>
   <td style="text-align:center;"> 103544.6 </td>
   <td style="text-align:center;"> 103239.4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BIC </td>
   <td style="text-align:center;"> 103559.0 </td>
   <td style="text-align:center;"> 103276.4 </td>
   <td style="text-align:center;"> 103559.0 </td>
   <td style="text-align:center;"> 103276.3 </td>
   <td style="text-align:center;"> 103560.2 </td>
   <td style="text-align:center;"> 103278.6 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RMSE </td>
   <td style="text-align:center;"> 3.90 </td>
   <td style="text-align:center;"> 3.87 </td>
   <td style="text-align:center;"> 3.90 </td>
   <td style="text-align:center;"> 3.87 </td>
   <td style="text-align:center;"> 3.90 </td>
   <td style="text-align:center;"> 3.87 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Std.Errors </td>
   <td style="text-align:center;"> by: state_f </td>
   <td style="text-align:center;"> by: state_f </td>
   <td style="text-align:center;"> by: state_f </td>
   <td style="text-align:center;"> by: state_f </td>
   <td style="text-align:center;"> by: state_f </td>
   <td style="text-align:center;"> by: state_f </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>　いずれのモデルも統計的に有意な処置効果は確認されていない。これらの結果を表として報告するには紙がもったいない気もする。これらの結果はOnline Appendixに回し、本文中には処置効果の点推定値と95%信頼区間を示せば良いだろう。</p>
<p>　{broom}の<code>tidy()</code>関数で推定結果のみを抽出し、それぞれオブジェクトとして格納しておこう。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>tidy_fit1 <span class="ot">&lt;-</span> <span class="fu">tidy</span>(did_fit1, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-2"><a href="#cb14-2"></a>tidy_fit2 <span class="ot">&lt;-</span> <span class="fu">tidy</span>(did_fit2, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-3"><a href="#cb14-3"></a>tidy_fit3 <span class="ot">&lt;-</span> <span class="fu">tidy</span>(did_fit3, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-4"><a href="#cb14-4"></a>tidy_fit4 <span class="ot">&lt;-</span> <span class="fu">tidy</span>(did_fit4, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-5"><a href="#cb14-5"></a>tidy_fit5 <span class="ot">&lt;-</span> <span class="fu">tidy</span>(did_fit5, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-6"><a href="#cb14-6"></a>tidy_fit6 <span class="ot">&lt;-</span> <span class="fu">tidy</span>(did_fit6, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>　全て確認する必要はないので、<code>tidy_fit1</code>のみを確認してみる。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a>tidy_fit1</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      term   estimate std.error  statistic   p.value conf.low conf.high df
1 shooting -0.5210841 0.6456718 -0.8070417 0.4235426 -1.81861  0.776442 49
  outcome
1 turnout</code></pre>
</div>
</div>
<p>　以上の6つの表形式オブジェクトを一つの表としてまとめる。それぞれのオブジェクトには<code>共変量の有無_処置変数の種類</code>の名前を付けよう。共変量なしのモデルは<code>M1</code>、ありのモデルは<code>M2</code>とする。処置変数は<code>shooting</code>の場合は<code>Tr1</code>、<code>fatal_shooting</code>は<code>Tr2</code>、<code>non_fatal_shooting</code>は<code>Tr3</code>とする。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>did_est1 <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">list</span>(<span class="st">"M1_Tr1"</span> <span class="ot">=</span> tidy_fit1,</span>
<span id="cb17-2"><a href="#cb17-2"></a>                           <span class="st">"M2_Tr1"</span> <span class="ot">=</span> tidy_fit2,</span>
<span id="cb17-3"><a href="#cb17-3"></a>                           <span class="st">"M1_Tr2"</span> <span class="ot">=</span> tidy_fit3,</span>
<span id="cb17-4"><a href="#cb17-4"></a>                           <span class="st">"M2_Tr2"</span> <span class="ot">=</span> tidy_fit4,</span>
<span id="cb17-5"><a href="#cb17-5"></a>                           <span class="st">"M1_Tr3"</span> <span class="ot">=</span> tidy_fit5,</span>
<span id="cb17-6"><a href="#cb17-6"></a>                           <span class="st">"M2_Tr3"</span> <span class="ot">=</span> tidy_fit6),</span>
<span id="cb17-7"><a href="#cb17-7"></a>                      <span class="at">.id =</span> <span class="st">"Model"</span>)</span>
<span id="cb17-8"><a href="#cb17-8"></a></span>
<span id="cb17-9"><a href="#cb17-9"></a>did_est1</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Model               term      estimate    std.error  statistic    p.value
1  M1_Tr1           shooting -5.210841e-01 6.456718e-01 -0.8070417 0.42354260
2  M2_Tr1           shooting -7.097922e-01 6.237320e-01 -1.1379763 0.26066411
3  M2_Tr1         population  8.028568e-06 5.688141e-06  1.4114574 0.16442833
4  M2_Tr1          non_white -3.483443e+01 1.557543e+01 -2.2364985 0.02990378
5  M2_Tr1   change_unem_rate  1.592020e-01 6.584450e-02  2.4178480 0.01937671
6  M1_Tr2     fatal_shooting -6.779229e-01 6.191749e-01 -1.0948810 0.27892152
7  M2_Tr2     fatal_shooting -9.179995e-01 6.576559e-01 -1.3958659 0.16904785
8  M2_Tr2         population  8.026778e-06 5.747531e-06  1.3965611 0.16883977
9  M2_Tr2          non_white -3.484436e+01 1.561829e+01 -2.2309975 0.03029042
10 M2_Tr2   change_unem_rate  1.591126e-01 6.591001e-02  2.4140886 0.01955574
11 M1_Tr3 non_fatal_shooting -2.387205e-01 1.093832e+00 -0.2182423 0.82814672
12 M2_Tr3 non_fatal_shooting -3.269742e-01 1.145303e+00 -0.2854915 0.77647098
13 M2_Tr3         population  7.821482e-06 5.712400e-06  1.3692110 0.17717684
14 M2_Tr3          non_white -3.481384e+01 1.561438e+01 -2.2296020 0.03038921
15 M2_Tr3   change_unem_rate  1.595359e-01 6.590170e-02  2.4208169 0.01923637
        conf.low     conf.high df outcome
1  -1.818610e+00  7.764420e-01 49 turnout
2  -1.963229e+00  5.436442e-01 49 turnout
3  -3.402178e-06  1.945932e-05 49 turnout
4  -6.613442e+01 -3.534428e+00 49 turnout
5   2.688251e-02  2.915215e-01 49 turnout
6  -1.922202e+00  5.663557e-01 49 turnout
7  -2.239609e+00  4.036096e-01 49 turnout
8  -3.523318e-06  1.957687e-05 49 turnout
9  -6.623047e+01 -3.458237e+00 49 turnout
10  2.666148e-02  2.915637e-01 49 turnout
11 -2.436859e+00  1.959418e+00 49 turnout
12 -2.628546e+00  1.974598e+00 49 turnout
13 -3.658017e-06  1.930098e-05 49 turnout
14 -6.619211e+01 -3.435580e+00 49 turnout
15  2.710152e-02  2.919704e-01 49 turnout</code></pre>
</div>
</div>
<p>　続いて、処置効果のみを抽出する。処置効果は<code>term</code>列の値が<code>"shooting"</code>、<code>"fatal_shooting"</code>、<code>"non_fatal_shooting"</code>のいずれかと一致する行であるため、<code>filter()</code>関数を使用する。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a>did_est1 <span class="ot">&lt;-</span> did_est1 <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2"></a>  <span class="fu">filter</span>(term <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"shooting"</span>, <span class="st">"fatal_shooting"</span>, <span class="st">"non_fatal_shooting"</span>))</span>
<span id="cb19-3"><a href="#cb19-3"></a></span>
<span id="cb19-4"><a href="#cb19-4"></a>did_est1</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Model               term   estimate std.error  statistic   p.value  conf.low
1 M1_Tr1           shooting -0.5210841 0.6456718 -0.8070417 0.4235426 -1.818610
2 M2_Tr1           shooting -0.7097922 0.6237320 -1.1379763 0.2606641 -1.963229
3 M1_Tr2     fatal_shooting -0.6779229 0.6191749 -1.0948810 0.2789215 -1.922202
4 M2_Tr2     fatal_shooting -0.9179995 0.6576559 -1.3958659 0.1690478 -2.239609
5 M1_Tr3 non_fatal_shooting -0.2387205 1.0938325 -0.2182423 0.8281467 -2.436859
6 M2_Tr3 non_fatal_shooting -0.3269742 1.1453027 -0.2854915 0.7764710 -2.628546
  conf.high df outcome
1 0.7764420 49 turnout
2 0.5436442 49 turnout
3 0.5663557 49 turnout
4 0.4036096 49 turnout
5 1.9594182 49 turnout
6 1.9745977 49 turnout</code></pre>
</div>
</div>
<p>　ちなみに<code>grepl()</code>関数を使うと、<code>"shooting"</code>が含まれる行を抽出することもできる。以下のコードは上記のコードと同じ機能をする。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a>did_est1 <span class="ot">&lt;-</span> did_est1 <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2"></a>  <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">"shooting"</span>, term))</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>　つづいて、<code>Model</code>列を<code>Model</code>と<code>Treat</code>列へ分割する。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>did_est1 <span class="ot">&lt;-</span> did_est1 <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2"></a>  <span class="fu">separate</span>(<span class="at">col  =</span> Model,</span>
<span id="cb22-3"><a href="#cb22-3"></a>           <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"Model"</span>, <span class="st">"Treat"</span>),</span>
<span id="cb22-4"><a href="#cb22-4"></a>           <span class="at">sep  =</span> <span class="st">"_"</span>)</span>
<span id="cb22-5"><a href="#cb22-5"></a></span>
<span id="cb22-6"><a href="#cb22-6"></a>did_est1</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Model Treat               term   estimate std.error  statistic   p.value
1    M1   Tr1           shooting -0.5210841 0.6456718 -0.8070417 0.4235426
2    M2   Tr1           shooting -0.7097922 0.6237320 -1.1379763 0.2606641
3    M1   Tr2     fatal_shooting -0.6779229 0.6191749 -1.0948810 0.2789215
4    M2   Tr2     fatal_shooting -0.9179995 0.6576559 -1.3958659 0.1690478
5    M1   Tr3 non_fatal_shooting -0.2387205 1.0938325 -0.2182423 0.8281467
6    M2   Tr3 non_fatal_shooting -0.3269742 1.1453027 -0.2854915 0.7764710
   conf.low conf.high df outcome
1 -1.818610 0.7764420 49 turnout
2 -1.963229 0.5436442 49 turnout
3 -1.922202 0.5663557 49 turnout
4 -2.239609 0.4036096 49 turnout
5 -2.436859 1.9594182 49 turnout
6 -2.628546 1.9745977 49 turnout</code></pre>
</div>
</div>
<p>　可視化に入る前に<code>Model</code>列と<code>Treat</code>列の値を修正する。<code>Model</code>列の値が<code>"M1"</code>なら<code>"County-Year FE"</code>に、それ以外なら<code>"County-Year FE + Covariates"</code>とリコーディングする。戻り値が2種類だから<code>if_else()</code>を使う。<code>Treat</code>列の場合、戻り値が3つなので、<code>recode()</code>か<code>case_when()</code>を使う。ここでは<code>recode()</code>を使ってリコーディングする。最後に<code>Model</code>と<code>Treat</code>を表示順番でfactor化し（<code>fct_inorder()</code>）、更に順番を逆転する（<code>fct_rev()</code>）。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a>did_est1 <span class="ot">&lt;-</span> did_est1 <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2"></a>  <span class="fu">mutate</span>(<span class="at">Model =</span> <span class="fu">if_else</span>(Model <span class="sc">==</span> <span class="st">"M1"</span>,</span>
<span id="cb24-3"><a href="#cb24-3"></a>                           <span class="st">"County-Year FE"</span>, </span>
<span id="cb24-4"><a href="#cb24-4"></a>                           <span class="st">"County-Year FE + Covariates"</span>),</span>
<span id="cb24-5"><a href="#cb24-5"></a>         <span class="at">Treat =</span> <span class="fu">recode</span>(Treat,</span>
<span id="cb24-6"><a href="#cb24-6"></a>                        <span class="st">"Tr1"</span> <span class="ot">=</span> <span class="st">"Any Shooting (t-1)"</span>,</span>
<span id="cb24-7"><a href="#cb24-7"></a>                        <span class="st">"Tr2"</span> <span class="ot">=</span> <span class="st">"Fatal Shooting (t-1)"</span>,</span>
<span id="cb24-8"><a href="#cb24-8"></a>                        <span class="st">"Tr3"</span> <span class="ot">=</span> <span class="st">"Nonfatal Shooting (t-1)"</span>),</span>
<span id="cb24-9"><a href="#cb24-9"></a>         <span class="at">Model =</span> <span class="fu">fct_rev</span>(<span class="fu">fct_inorder</span>(Model)),</span>
<span id="cb24-10"><a href="#cb24-10"></a>         <span class="at">Treat =</span> <span class="fu">fct_rev</span>(<span class="fu">fct_inorder</span>(Treat)))</span>
<span id="cb24-11"><a href="#cb24-11"></a></span>
<span id="cb24-12"><a href="#cb24-12"></a>did_est1</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Model                   Treat               term
1              County-Year FE      Any Shooting (t-1)           shooting
2 County-Year FE + Covariates      Any Shooting (t-1)           shooting
3              County-Year FE    Fatal Shooting (t-1)     fatal_shooting
4 County-Year FE + Covariates    Fatal Shooting (t-1)     fatal_shooting
5              County-Year FE Nonfatal Shooting (t-1) non_fatal_shooting
6 County-Year FE + Covariates Nonfatal Shooting (t-1) non_fatal_shooting
    estimate std.error  statistic   p.value  conf.low conf.high df outcome
1 -0.5210841 0.6456718 -0.8070417 0.4235426 -1.818610 0.7764420 49 turnout
2 -0.7097922 0.6237320 -1.1379763 0.2606641 -1.963229 0.5436442 49 turnout
3 -0.6779229 0.6191749 -1.0948810 0.2789215 -1.922202 0.5663557 49 turnout
4 -0.9179995 0.6576559 -1.3958659 0.1690478 -2.239609 0.4036096 49 turnout
5 -0.2387205 1.0938325 -0.2182423 0.8281467 -2.436859 1.9594182 49 turnout
6 -0.3269742 1.1453027 -0.2854915 0.7764710 -2.628546 1.9745977 49 turnout</code></pre>
</div>
</div>
<p>　それでは{ggplot2}を使ってpoint-rangeプロットを作成してみよう。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a>did_est1 <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3"></a>  <span class="co"># x = 0の箇所に垂直線を引く。垂直線は破線（linetype = 2）とする。</span></span>
<span id="cb26-4"><a href="#cb26-4"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">xmin =</span> conf.low, <span class="at">xmax =</span> conf.high,</span>
<span id="cb26-6"><a href="#cb26-6"></a>                      <span class="at">y =</span> Treat, <span class="at">color =</span> Model),</span>
<span id="cb26-7"><a href="#cb26-7"></a>                  <span class="at">position =</span> <span class="fu">position_dodge2</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb26-8"><a href="#cb26-8"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Change in Turnout (%p)"</span>, <span class="at">y =</span> <span class="st">""</span>, <span class="at">color =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb26-9"><a href="#cb26-9"></a>  <span class="co"># 色を指定する。</span></span>
<span id="cb26-10"><a href="#cb26-10"></a>  <span class="co"># Modelの値が County-Year FE なら黒、</span></span>
<span id="cb26-11"><a href="#cb26-11"></a>  <span class="co"># County-Year FE + Covariates ならグレー、</span></span>
<span id="cb26-12"><a href="#cb26-12"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"County-Year FE"</span> <span class="ot">=</span> <span class="st">"black"</span>, </span>
<span id="cb26-13"><a href="#cb26-13"></a>                                <span class="st">"County-Year FE + Covariates"</span> <span class="ot">=</span> <span class="st">"gray50"</span>)) <span class="sc">+</span></span>
<span id="cb26-14"><a href="#cb26-14"></a>  <span class="co"># 横軸の下限と上限を-10〜10とする。</span></span>
<span id="cb26-15"><a href="#cb26-15"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb26-16"><a href="#cb26-16"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb26-17"><a href="#cb26-17"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="2700"></p>
</figure>
</div>
</div>
</div>
<p>　元の論文を見ると、点の上に点推定値が書かれているが、私たちもこれを真似してみよう。文字列をプロットするレイヤーは<code>geom_text()</code>と<code>geom_label()</code>、<code>annotate()</code>があるが、ここでは<code>geom_text()</code>を使用する。文字列が表示される横軸上の位置（<code>x</code>）と縦軸上の位置（<code>y</code>）、そして出力する文字列（<code>label</code>）をマッピングする。点推定値は3桁まで出力したいので、<code>sprintf()</code>を使って、3桁に丸める。ただし、これだけだと点と文字が重なってしまう。<code>vjust</code>を<code>-0.75</code>にすることで、出力する文字列を点の位置を上の方向へ若干ずらすことができる。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a>did_est1 <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">xmin =</span> conf.low, <span class="at">xmax =</span> conf.high,</span>
<span id="cb27-5"><a href="#cb27-5"></a>                      <span class="at">y =</span> Treat, <span class="at">color =</span> Model),</span>
<span id="cb27-6"><a href="#cb27-6"></a>                  <span class="at">position =</span> <span class="fu">position_dodge2</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">y =</span> Treat, <span class="at">color =</span> Model, </span>
<span id="cb27-8"><a href="#cb27-8"></a>                <span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, estimate)),</span>
<span id="cb27-9"><a href="#cb27-9"></a>            <span class="at">position =</span> <span class="fu">position_dodge2</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>),</span>
<span id="cb27-10"><a href="#cb27-10"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.75</span>) <span class="sc">+</span></span>
<span id="cb27-11"><a href="#cb27-11"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Change in Turnout (%p)"</span>, <span class="at">y =</span> <span class="st">""</span>, <span class="at">color =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb27-12"><a href="#cb27-12"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"County-Year FE"</span> <span class="ot">=</span> <span class="st">"black"</span>, </span>
<span id="cb27-13"><a href="#cb27-13"></a>                                <span class="st">"County-Year FE + Covariates"</span> <span class="ot">=</span> <span class="st">"gray50"</span>)) <span class="sc">+</span></span>
<span id="cb27-14"><a href="#cb27-14"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb27-15"><a href="#cb27-15"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb27-16"><a href="#cb27-16"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="2700"></p>
</figure>
</div>
</div>
</div>
<p>　ちなみにこのコードを見ると、<code>geom_pointrange()</code>と<code>geom_text()</code>は<code>x</code>、<code>y</code>、<code>color</code>を共有しているので、<code>ggplot()</code>内でマッピングすることもできる。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a>did_est1 <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">y =</span> Treat, <span class="at">color =</span> Model)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> conf.low, <span class="at">xmax =</span> conf.high),</span>
<span id="cb28-5"><a href="#cb28-5"></a>                  <span class="at">position =</span> <span class="fu">position_dodge2</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, estimate)),</span>
<span id="cb28-7"><a href="#cb28-7"></a>            <span class="at">position =</span> <span class="fu">position_dodge2</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>),</span>
<span id="cb28-8"><a href="#cb28-8"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.75</span>) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Change in Turnout (%p)"</span>, <span class="at">y =</span> <span class="st">""</span>, <span class="at">color =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"County-Year FE"</span> <span class="ot">=</span> <span class="st">"black"</span>, </span>
<span id="cb28-11"><a href="#cb28-11"></a>                                <span class="st">"County-Year FE + Covariates"</span> <span class="ot">=</span> <span class="st">"gray50"</span>)) <span class="sc">+</span></span>
<span id="cb28-12"><a href="#cb28-12"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb28-13"><a href="#cb28-13"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb28-14"><a href="#cb28-14"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>　続いて、民主党候補者の得票率（<code>demvote</code>）を応答変数として6つのモデルを推定し、同じ作業を繰り返す。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a>did_fit7 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(demvote <span class="sc">~</span> shooting, </span>
<span id="cb29-2"><a href="#cb29-2"></a>                      <span class="at">data          =</span> did_df, </span>
<span id="cb29-3"><a href="#cb29-3"></a>                      <span class="at">fixed_effects =</span> <span class="sc">~</span>year_f <span class="sc">+</span> county_f,</span>
<span id="cb29-4"><a href="#cb29-4"></a>                      <span class="at">clusters      =</span> state_f,</span>
<span id="cb29-5"><a href="#cb29-5"></a>                      <span class="at">se_type       =</span> <span class="st">"stata"</span>)</span>
<span id="cb29-6"><a href="#cb29-6"></a></span>
<span id="cb29-7"><a href="#cb29-7"></a>did_fit8 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(demvote <span class="sc">~</span> shooting <span class="sc">+</span> </span>
<span id="cb29-8"><a href="#cb29-8"></a>                        population <span class="sc">+</span> non_white <span class="sc">+</span> change_unem_rate, </span>
<span id="cb29-9"><a href="#cb29-9"></a>                      <span class="at">data          =</span> did_df, </span>
<span id="cb29-10"><a href="#cb29-10"></a>                      <span class="at">fixed_effects =</span> <span class="sc">~</span>year_f <span class="sc">+</span> county_f,</span>
<span id="cb29-11"><a href="#cb29-11"></a>                      <span class="at">clusters      =</span> state_f,</span>
<span id="cb29-12"><a href="#cb29-12"></a>                      <span class="at">se_type       =</span> <span class="st">"stata"</span>)</span>
<span id="cb29-13"><a href="#cb29-13"></a></span>
<span id="cb29-14"><a href="#cb29-14"></a>did_fit9 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(demvote <span class="sc">~</span> fatal_shooting, </span>
<span id="cb29-15"><a href="#cb29-15"></a>                      <span class="at">data          =</span> did_df, </span>
<span id="cb29-16"><a href="#cb29-16"></a>                      <span class="at">fixed_effects =</span> <span class="sc">~</span>year_f <span class="sc">+</span> county_f,</span>
<span id="cb29-17"><a href="#cb29-17"></a>                      <span class="at">clusters      =</span> state_f,</span>
<span id="cb29-18"><a href="#cb29-18"></a>                      <span class="at">se_type       =</span> <span class="st">"stata"</span>)</span>
<span id="cb29-19"><a href="#cb29-19"></a></span>
<span id="cb29-20"><a href="#cb29-20"></a>did_fit10 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(demvote <span class="sc">~</span> fatal_shooting <span class="sc">+</span> </span>
<span id="cb29-21"><a href="#cb29-21"></a>                         population <span class="sc">+</span> non_white <span class="sc">+</span> change_unem_rate, </span>
<span id="cb29-22"><a href="#cb29-22"></a>                       <span class="at">data          =</span> did_df, </span>
<span id="cb29-23"><a href="#cb29-23"></a>                       <span class="at">fixed_effects =</span> <span class="sc">~</span>year_f <span class="sc">+</span> county_f,</span>
<span id="cb29-24"><a href="#cb29-24"></a>                       <span class="at">clusters      =</span> state_f,</span>
<span id="cb29-25"><a href="#cb29-25"></a>                       <span class="at">se_type       =</span> <span class="st">"stata"</span>)</span>
<span id="cb29-26"><a href="#cb29-26"></a></span>
<span id="cb29-27"><a href="#cb29-27"></a>did_fit11 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(demvote <span class="sc">~</span> non_fatal_shooting, </span>
<span id="cb29-28"><a href="#cb29-28"></a>                       <span class="at">data          =</span> did_df, </span>
<span id="cb29-29"><a href="#cb29-29"></a>                       <span class="at">fixed_effects =</span> <span class="sc">~</span>year_f <span class="sc">+</span> county_f,</span>
<span id="cb29-30"><a href="#cb29-30"></a>                       <span class="at">clusters      =</span> state_f,</span>
<span id="cb29-31"><a href="#cb29-31"></a>                       <span class="at">se_type       =</span> <span class="st">"stata"</span>)</span>
<span id="cb29-32"><a href="#cb29-32"></a></span>
<span id="cb29-33"><a href="#cb29-33"></a>did_fit12 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(demvote <span class="sc">~</span> non_fatal_shooting <span class="sc">+</span> </span>
<span id="cb29-34"><a href="#cb29-34"></a>                         population <span class="sc">+</span> non_white <span class="sc">+</span> change_unem_rate, </span>
<span id="cb29-35"><a href="#cb29-35"></a>                       <span class="at">data          =</span> did_df, </span>
<span id="cb29-36"><a href="#cb29-36"></a>                       <span class="at">fixed_effects =</span> <span class="sc">~</span>year_f <span class="sc">+</span> county_f,</span>
<span id="cb29-37"><a href="#cb29-37"></a>                       <span class="at">clusters      =</span> state_f,</span>
<span id="cb29-38"><a href="#cb29-38"></a>                       <span class="at">se_type       =</span> <span class="st">"stata"</span>)</span>
<span id="cb29-39"><a href="#cb29-39"></a></span>
<span id="cb29-40"><a href="#cb29-40"></a><span class="fu">modelsummary</span>(<span class="fu">list</span>(<span class="st">"Model 7"</span>  <span class="ot">=</span> did_fit7,  <span class="st">"Model 8"</span>  <span class="ot">=</span> did_fit8, </span>
<span id="cb29-41"><a href="#cb29-41"></a>                  <span class="st">"Model 9"</span>  <span class="ot">=</span> did_fit9,  <span class="st">"Model 10"</span> <span class="ot">=</span> did_fit10, </span>
<span id="cb29-42"><a href="#cb29-42"></a>                  <span class="st">"Model 11"</span> <span class="ot">=</span> did_fit11, <span class="st">"Model 12"</span> <span class="ot">=</span> did_fit12))</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> Model 7 </th>
   <th style="text-align:center;"> Model 8 </th>
   <th style="text-align:center;"> Model 9 </th>
   <th style="text-align:center;"> Model 10 </th>
   <th style="text-align:center;"> Model 11 </th>
   <th style="text-align:center;"> Model 12 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> shooting </td>
   <td style="text-align:center;"> 4.513 </td>
   <td style="text-align:center;"> 2.364 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;"> (0.875) </td>
   <td style="text-align:center;"> (0.737) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> population </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.000 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.000 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.000 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (0.000) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (0.000) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (0.000) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> non_white </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 86.873 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 86.866 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 86.796 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (17.863) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (17.855) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (17.855) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> change_unem_rate </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> −0.139 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> −0.139 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> −0.140 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (0.127) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (0.128) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (0.127) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> fatal_shooting </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 4.404 </td>
   <td style="text-align:center;"> 1.782 </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (1.092) </td>
   <td style="text-align:center;"> (0.836) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> non_fatal_shooting </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 4.217 </td>
   <td style="text-align:center;"> 2.930 </td>
  </tr>
  <tr>
   <td style="text-align:left;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px"> (1.298) </td>
   <td style="text-align:center;box-shadow: 0px 1px"> (1.037) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Num.Obs. </td>
   <td style="text-align:center;"> 18627 </td>
   <td style="text-align:center;"> 18627 </td>
   <td style="text-align:center;"> 18627 </td>
   <td style="text-align:center;"> 18627 </td>
   <td style="text-align:center;"> 18627 </td>
   <td style="text-align:center;"> 18627 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> R2 </td>
   <td style="text-align:center;"> 0.882 </td>
   <td style="text-align:center;"> 0.894 </td>
   <td style="text-align:center;"> 0.882 </td>
   <td style="text-align:center;"> 0.894 </td>
   <td style="text-align:center;"> 0.882 </td>
   <td style="text-align:center;"> 0.894 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> AIC </td>
   <td style="text-align:center;"> 110745.2 </td>
   <td style="text-align:center;"> 108755.4 </td>
   <td style="text-align:center;"> 110772.0 </td>
   <td style="text-align:center;"> 108768.2 </td>
   <td style="text-align:center;"> 110786.5 </td>
   <td style="text-align:center;"> 108762.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BIC </td>
   <td style="text-align:center;"> 110760.8 </td>
   <td style="text-align:center;"> 108794.6 </td>
   <td style="text-align:center;"> 110787.7 </td>
   <td style="text-align:center;"> 108807.3 </td>
   <td style="text-align:center;"> 110802.2 </td>
   <td style="text-align:center;"> 108801.3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RMSE </td>
   <td style="text-align:center;"> 4.73 </td>
   <td style="text-align:center;"> 4.48 </td>
   <td style="text-align:center;"> 4.73 </td>
   <td style="text-align:center;"> 4.48 </td>
   <td style="text-align:center;"> 4.73 </td>
   <td style="text-align:center;"> 4.48 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Std.Errors </td>
   <td style="text-align:center;"> by: state_f </td>
   <td style="text-align:center;"> by: state_f </td>
   <td style="text-align:center;"> by: state_f </td>
   <td style="text-align:center;"> by: state_f </td>
   <td style="text-align:center;"> by: state_f </td>
   <td style="text-align:center;"> by: state_f </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>　今回はいずれも統計的に有意な結果が得られている。例えば、モデル7（<code>did_fit7</code>）の場合、処置効果の推定値は4.513である。これは学校内銃撃事件が発生したカウンティーの場合、大統領選挙において民主党候補者の得票率が約4.513%p増加することを意味する。</p>
<p>　以上の結果を図としてまとめてみよう。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a>tidy_fit7  <span class="ot">&lt;-</span> <span class="fu">tidy</span>(did_fit7)</span>
<span id="cb30-2"><a href="#cb30-2"></a>tidy_fit8  <span class="ot">&lt;-</span> <span class="fu">tidy</span>(did_fit8)</span>
<span id="cb30-3"><a href="#cb30-3"></a>tidy_fit9  <span class="ot">&lt;-</span> <span class="fu">tidy</span>(did_fit9)</span>
<span id="cb30-4"><a href="#cb30-4"></a>tidy_fit10 <span class="ot">&lt;-</span> <span class="fu">tidy</span>(did_fit10)</span>
<span id="cb30-5"><a href="#cb30-5"></a>tidy_fit11 <span class="ot">&lt;-</span> <span class="fu">tidy</span>(did_fit11)</span>
<span id="cb30-6"><a href="#cb30-6"></a>tidy_fit12 <span class="ot">&lt;-</span> <span class="fu">tidy</span>(did_fit12)</span>
<span id="cb30-7"><a href="#cb30-7"></a></span>
<span id="cb30-8"><a href="#cb30-8"></a>did_est2 <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">list</span>(<span class="st">"M1_Tr1"</span> <span class="ot">=</span> tidy_fit7,</span>
<span id="cb30-9"><a href="#cb30-9"></a>                           <span class="st">"M2_Tr1"</span> <span class="ot">=</span> tidy_fit8,</span>
<span id="cb30-10"><a href="#cb30-10"></a>                           <span class="st">"M1_Tr2"</span> <span class="ot">=</span> tidy_fit9,</span>
<span id="cb30-11"><a href="#cb30-11"></a>                           <span class="st">"M2_Tr2"</span> <span class="ot">=</span> tidy_fit10,</span>
<span id="cb30-12"><a href="#cb30-12"></a>                           <span class="st">"M1_Tr3"</span> <span class="ot">=</span> tidy_fit11,</span>
<span id="cb30-13"><a href="#cb30-13"></a>                           <span class="st">"M2_Tr3"</span> <span class="ot">=</span> tidy_fit12),</span>
<span id="cb30-14"><a href="#cb30-14"></a>                      <span class="at">.id =</span> <span class="st">"Model"</span>)</span>
<span id="cb30-15"><a href="#cb30-15"></a></span>
<span id="cb30-16"><a href="#cb30-16"></a>did_est2</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Model               term      estimate    std.error statistic      p.value
1  M1_Tr1           shooting  4.513237e+00 8.752702e-01  5.156393 4.514820e-06
2  M2_Tr1           shooting  2.363839e+00 7.367346e-01  3.208536 2.353748e-03
3  M2_Tr1         population  3.174252e-05 6.778757e-06  4.682646 2.275534e-05
4  M2_Tr1          non_white  8.687344e+01 1.786287e+01  4.863352 1.234074e-05
5  M2_Tr1   change_unem_rate -1.389392e-01 1.274198e-01 -1.090405 2.808682e-01
6  M1_Tr2     fatal_shooting  4.404109e+00 1.091944e+00  4.033274 1.920110e-04
7  M2_Tr2     fatal_shooting  1.782393e+00 8.363792e-01  2.131083 3.812471e-02
8  M2_Tr2         population  3.206812e-05 6.801197e-06  4.715070 2.039958e-05
9  M2_Tr2          non_white  8.686629e+01 1.785535e+01  4.865000 1.227169e-05
10 M2_Tr2   change_unem_rate -1.392341e-01 1.275138e-01 -1.091914 2.802109e-01
11 M1_Tr3 non_fatal_shooting  4.216683e+00 1.298056e+00  3.248460 2.098382e-03
12 M2_Tr3 non_fatal_shooting  2.929866e+00 1.037217e+00  2.824737 6.825655e-03
13 M2_Tr3         population  3.229215e-05 6.717999e-06  4.806810 1.495567e-05
14 M2_Tr3          non_white  8.679618e+01 1.785514e+01  4.861131 1.243440e-05
15 M2_Tr3   change_unem_rate -1.400321e-01 1.274994e-01 -1.098296 2.774427e-01
        conf.low    conf.high df outcome
1   2.754316e+00 6.272159e+00 49 demvote
2   8.833157e-01 3.844363e+00 49 demvote
3   1.812010e-05 4.536494e-05 49 demvote
4   5.097665e+01 1.227702e+02 49 demvote
5  -3.949989e-01 1.171206e-01 49 demvote
6   2.209766e+00 6.598453e+00 49 demvote
7   1.016261e-01 3.463160e+00 49 demvote
8   1.840061e-05 4.573564e-05 49 demvote
9   5.098461e+01 1.227480e+02 49 demvote
10 -3.954828e-01 1.170146e-01 49 demvote
11  1.608142e+00 6.825225e+00 49 demvote
12  8.454996e-01 5.014232e+00 49 demvote
13  1.879182e-05 4.579247e-05 49 demvote
14  5.091493e+01 1.226774e+02 49 demvote
15 -3.962518e-01 1.161876e-01 49 demvote</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a>did_est2 <span class="ot">&lt;-</span> did_est2 <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2"></a>  <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">"shooting"</span>, term))</span>
<span id="cb32-3"><a href="#cb32-3"></a></span>
<span id="cb32-4"><a href="#cb32-4"></a>did_est2</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Model               term estimate std.error statistic      p.value  conf.low
1 M1_Tr1           shooting 4.513237 0.8752702  5.156393 4.514820e-06 2.7543158
2 M2_Tr1           shooting 2.363839 0.7367346  3.208536 2.353748e-03 0.8833157
3 M1_Tr2     fatal_shooting 4.404109 1.0919440  4.033274 1.920110e-04 2.2097656
4 M2_Tr2     fatal_shooting 1.782393 0.8363792  2.131083 3.812471e-02 0.1016261
5 M1_Tr3 non_fatal_shooting 4.216683 1.2980560  3.248460 2.098382e-03 1.6081422
6 M2_Tr3 non_fatal_shooting 2.929866 1.0372173  2.824737 6.825655e-03 0.8454996
  conf.high df outcome
1  6.272159 49 demvote
2  3.844363 49 demvote
3  6.598453 49 demvote
4  3.463160 49 demvote
5  6.825225 49 demvote
6  5.014232 49 demvote</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a>did_est2 <span class="ot">&lt;-</span> did_est2 <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2"></a>  <span class="fu">separate</span>(<span class="at">col  =</span> Model,</span>
<span id="cb34-3"><a href="#cb34-3"></a>           <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"Model"</span>, <span class="st">"Treat"</span>),</span>
<span id="cb34-4"><a href="#cb34-4"></a>           <span class="at">sep  =</span> <span class="st">"_"</span>)</span>
<span id="cb34-5"><a href="#cb34-5"></a></span>
<span id="cb34-6"><a href="#cb34-6"></a>did_est2</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Model Treat               term estimate std.error statistic      p.value
1    M1   Tr1           shooting 4.513237 0.8752702  5.156393 4.514820e-06
2    M2   Tr1           shooting 2.363839 0.7367346  3.208536 2.353748e-03
3    M1   Tr2     fatal_shooting 4.404109 1.0919440  4.033274 1.920110e-04
4    M2   Tr2     fatal_shooting 1.782393 0.8363792  2.131083 3.812471e-02
5    M1   Tr3 non_fatal_shooting 4.216683 1.2980560  3.248460 2.098382e-03
6    M2   Tr3 non_fatal_shooting 2.929866 1.0372173  2.824737 6.825655e-03
   conf.low conf.high df outcome
1 2.7543158  6.272159 49 demvote
2 0.8833157  3.844363 49 demvote
3 2.2097656  6.598453 49 demvote
4 0.1016261  3.463160 49 demvote
5 1.6081422  6.825225 49 demvote
6 0.8454996  5.014232 49 demvote</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a>did_est2 <span class="ot">&lt;-</span> did_est2 <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="#cb36-2"></a>  <span class="fu">mutate</span>(<span class="at">Model =</span> <span class="fu">if_else</span>(Model <span class="sc">==</span> <span class="st">"M1"</span>,</span>
<span id="cb36-3"><a href="#cb36-3"></a>                           <span class="st">"County-Year FE"</span>, </span>
<span id="cb36-4"><a href="#cb36-4"></a>                           <span class="st">"County-Year FE + Covariates"</span>),</span>
<span id="cb36-5"><a href="#cb36-5"></a>         <span class="at">Treat =</span> <span class="fu">recode</span>(Treat,</span>
<span id="cb36-6"><a href="#cb36-6"></a>                        <span class="st">"Tr1"</span> <span class="ot">=</span> <span class="st">"Any Shooting (t-1)"</span>,</span>
<span id="cb36-7"><a href="#cb36-7"></a>                        <span class="st">"Tr2"</span> <span class="ot">=</span> <span class="st">"Fatal Shooting (t-1)"</span>,</span>
<span id="cb36-8"><a href="#cb36-8"></a>                        <span class="st">"Tr3"</span> <span class="ot">=</span> <span class="st">"Nonfatal Shooting (t-1)"</span>),</span>
<span id="cb36-9"><a href="#cb36-9"></a>         <span class="at">Model =</span> <span class="fu">fct_rev</span>(<span class="fu">fct_inorder</span>(Model)),</span>
<span id="cb36-10"><a href="#cb36-10"></a>         <span class="at">Treat =</span> <span class="fu">fct_rev</span>(<span class="fu">fct_inorder</span>(Treat)))</span>
<span id="cb36-11"><a href="#cb36-11"></a></span>
<span id="cb36-12"><a href="#cb36-12"></a>did_est2</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Model                   Treat               term
1              County-Year FE      Any Shooting (t-1)           shooting
2 County-Year FE + Covariates      Any Shooting (t-1)           shooting
3              County-Year FE    Fatal Shooting (t-1)     fatal_shooting
4 County-Year FE + Covariates    Fatal Shooting (t-1)     fatal_shooting
5              County-Year FE Nonfatal Shooting (t-1) non_fatal_shooting
6 County-Year FE + Covariates Nonfatal Shooting (t-1) non_fatal_shooting
  estimate std.error statistic      p.value  conf.low conf.high df outcome
1 4.513237 0.8752702  5.156393 4.514820e-06 2.7543158  6.272159 49 demvote
2 2.363839 0.7367346  3.208536 2.353748e-03 0.8833157  3.844363 49 demvote
3 4.404109 1.0919440  4.033274 1.920110e-04 2.2097656  6.598453 49 demvote
4 1.782393 0.8363792  2.131083 3.812471e-02 0.1016261  3.463160 49 demvote
5 4.216683 1.2980560  3.248460 2.098382e-03 1.6081422  6.825225 49 demvote
6 2.929866 1.0372173  2.824737 6.825655e-03 0.8454996  5.014232 49 demvote</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a>did_est2 <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">xmin =</span> conf.low, <span class="at">xmax =</span> conf.high,</span>
<span id="cb38-5"><a href="#cb38-5"></a>                      <span class="at">y =</span> Treat, <span class="at">color =</span> Model),</span>
<span id="cb38-6"><a href="#cb38-6"></a>                  <span class="at">position =</span> <span class="fu">position_dodge2</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">y =</span> Treat, <span class="at">color =</span> Model, </span>
<span id="cb38-8"><a href="#cb38-8"></a>                <span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, estimate)),</span>
<span id="cb38-9"><a href="#cb38-9"></a>            <span class="at">position =</span> <span class="fu">position_dodge2</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>),</span>
<span id="cb38-10"><a href="#cb38-10"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.75</span>) <span class="sc">+</span></span>
<span id="cb38-11"><a href="#cb38-11"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Change in Democratic Vote Share (%p)"</span>, <span class="at">y =</span> <span class="st">""</span>, <span class="at">color =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb38-12"><a href="#cb38-12"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"County-Year FE"</span> <span class="ot">=</span> <span class="st">"black"</span>, </span>
<span id="cb38-13"><a href="#cb38-13"></a>                                <span class="st">"County-Year FE + Covariates"</span> <span class="ot">=</span> <span class="st">"gray50"</span>)) <span class="sc">+</span></span>
<span id="cb38-14"><a href="#cb38-14"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb38-15"><a href="#cb38-15"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb38-16"><a href="#cb38-16"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="2700"></p>
</figure>
</div>
</div>
</div>
<p>　最後に、これまで作成した2つの図を一つにまとめてみよう。<code>bind_rows()</code>関数を使い、それぞれの表に識別子（<code>Outcome</code>）を与える。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a>did_est <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">list</span>(<span class="st">"Out1"</span> <span class="ot">=</span> did_est1,</span>
<span id="cb39-2"><a href="#cb39-2"></a>                          <span class="st">"Out2"</span> <span class="ot">=</span> did_est2),</span>
<span id="cb39-3"><a href="#cb39-3"></a>                     <span class="at">.id =</span> <span class="st">"Outcome"</span>)</span>
<span id="cb39-4"><a href="#cb39-4"></a></span>
<span id="cb39-5"><a href="#cb39-5"></a>did_est</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Outcome                       Model                   Treat
1     Out1              County-Year FE      Any Shooting (t-1)
2     Out1 County-Year FE + Covariates      Any Shooting (t-1)
3     Out1              County-Year FE    Fatal Shooting (t-1)
4     Out1 County-Year FE + Covariates    Fatal Shooting (t-1)
5     Out1              County-Year FE Nonfatal Shooting (t-1)
6     Out1 County-Year FE + Covariates Nonfatal Shooting (t-1)
7     Out2              County-Year FE      Any Shooting (t-1)
8     Out2 County-Year FE + Covariates      Any Shooting (t-1)
9     Out2              County-Year FE    Fatal Shooting (t-1)
10    Out2 County-Year FE + Covariates    Fatal Shooting (t-1)
11    Out2              County-Year FE Nonfatal Shooting (t-1)
12    Out2 County-Year FE + Covariates Nonfatal Shooting (t-1)
                 term   estimate std.error  statistic      p.value   conf.low
1            shooting -0.5210841 0.6456718 -0.8070417 4.235426e-01 -1.8186103
2            shooting -0.7097922 0.6237320 -1.1379763 2.606641e-01 -1.9632286
3      fatal_shooting -0.6779229 0.6191749 -1.0948810 2.789215e-01 -1.9222015
4      fatal_shooting -0.9179995 0.6576559 -1.3958659 1.690478e-01 -2.2396086
5  non_fatal_shooting -0.2387205 1.0938325 -0.2182423 8.281467e-01 -2.4368592
6  non_fatal_shooting -0.3269742 1.1453027 -0.2854915 7.764710e-01 -2.6285461
7            shooting  4.5132372 0.8752702  5.1563930 4.514820e-06  2.7543158
8            shooting  2.3638394 0.7367346  3.2085357 2.353748e-03  0.8833157
9      fatal_shooting  4.4041092 1.0919440  4.0332738 1.920110e-04  2.2097656
10     fatal_shooting  1.7823931 0.8363792  2.1310825 3.812471e-02  0.1016261
11 non_fatal_shooting  4.2166835 1.2980560  3.2484602 2.098382e-03  1.6081422
12 non_fatal_shooting  2.9298657 1.0372173  2.8247368 6.825655e-03  0.8454996
   conf.high df outcome
1  0.7764420 49 turnout
2  0.5436442 49 turnout
3  0.5663557 49 turnout
4  0.4036096 49 turnout
5  1.9594182 49 turnout
6  1.9745977 49 turnout
7  6.2721585 49 demvote
8  3.8443631 49 demvote
9  6.5984529 49 demvote
10 3.4631600 49 demvote
11 6.8252248 49 demvote
12 5.0142319 49 demvote</code></pre>
</div>
</div>
<p>　<code>Outcome</code>列のリコーディングし、factor化する。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>did_est <span class="ot">&lt;-</span> did_est <span class="sc">|&gt;</span></span>
<span id="cb41-2"><a href="#cb41-2"></a>  <span class="fu">mutate</span>(<span class="at">Outcome =</span> <span class="fu">if_else</span>(Outcome <span class="sc">==</span> <span class="st">"Out1"</span>,</span>
<span id="cb41-3"><a href="#cb41-3"></a>                           <span class="st">"Change in Turnout (%p)"</span>,</span>
<span id="cb41-4"><a href="#cb41-4"></a>                           <span class="st">"Change in Democratic Vote Share (%p)"</span>),</span>
<span id="cb41-5"><a href="#cb41-5"></a>         <span class="at">Outcome =</span> <span class="fu">fct_inorder</span>(Outcome))</span>
<span id="cb41-6"><a href="#cb41-6"></a></span>
<span id="cb41-7"><a href="#cb41-7"></a>did_est</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                Outcome                       Model
1                Change in Turnout (%p)              County-Year FE
2                Change in Turnout (%p) County-Year FE + Covariates
3                Change in Turnout (%p)              County-Year FE
4                Change in Turnout (%p) County-Year FE + Covariates
5                Change in Turnout (%p)              County-Year FE
6                Change in Turnout (%p) County-Year FE + Covariates
7  Change in Democratic Vote Share (%p)              County-Year FE
8  Change in Democratic Vote Share (%p) County-Year FE + Covariates
9  Change in Democratic Vote Share (%p)              County-Year FE
10 Change in Democratic Vote Share (%p) County-Year FE + Covariates
11 Change in Democratic Vote Share (%p)              County-Year FE
12 Change in Democratic Vote Share (%p) County-Year FE + Covariates
                     Treat               term   estimate std.error  statistic
1       Any Shooting (t-1)           shooting -0.5210841 0.6456718 -0.8070417
2       Any Shooting (t-1)           shooting -0.7097922 0.6237320 -1.1379763
3     Fatal Shooting (t-1)     fatal_shooting -0.6779229 0.6191749 -1.0948810
4     Fatal Shooting (t-1)     fatal_shooting -0.9179995 0.6576559 -1.3958659
5  Nonfatal Shooting (t-1) non_fatal_shooting -0.2387205 1.0938325 -0.2182423
6  Nonfatal Shooting (t-1) non_fatal_shooting -0.3269742 1.1453027 -0.2854915
7       Any Shooting (t-1)           shooting  4.5132372 0.8752702  5.1563930
8       Any Shooting (t-1)           shooting  2.3638394 0.7367346  3.2085357
9     Fatal Shooting (t-1)     fatal_shooting  4.4041092 1.0919440  4.0332738
10    Fatal Shooting (t-1)     fatal_shooting  1.7823931 0.8363792  2.1310825
11 Nonfatal Shooting (t-1) non_fatal_shooting  4.2166835 1.2980560  3.2484602
12 Nonfatal Shooting (t-1) non_fatal_shooting  2.9298657 1.0372173  2.8247368
        p.value   conf.low conf.high df outcome
1  4.235426e-01 -1.8186103 0.7764420 49 turnout
2  2.606641e-01 -1.9632286 0.5436442 49 turnout
3  2.789215e-01 -1.9222015 0.5663557 49 turnout
4  1.690478e-01 -2.2396086 0.4036096 49 turnout
5  8.281467e-01 -2.4368592 1.9594182 49 turnout
6  7.764710e-01 -2.6285461 1.9745977 49 turnout
7  4.514820e-06  2.7543158 6.2721585 49 demvote
8  2.353748e-03  0.8833157 3.8443631 49 demvote
9  1.920110e-04  2.2097656 6.5984529 49 demvote
10 3.812471e-02  0.1016261 3.4631600 49 demvote
11 2.098382e-03  1.6081422 6.8252248 49 demvote
12 6.825655e-03  0.8454996 5.0142319 49 demvote</code></pre>
</div>
</div>
<p>　図の作り方はこれまでと変わらないが、ファセット分割を行うため、<code>facet_wrap()</code>レイヤーを追加する。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a>did_est <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href="#cb43-2"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">xmin =</span> conf.low, <span class="at">xmax =</span> conf.high,</span>
<span id="cb43-5"><a href="#cb43-5"></a>                      <span class="at">y =</span> Treat, <span class="at">color =</span> Model),</span>
<span id="cb43-6"><a href="#cb43-6"></a>                  <span class="at">position =</span> <span class="fu">position_dodge2</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb43-7"><a href="#cb43-7"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">y =</span> Treat, <span class="at">color =</span> Model, </span>
<span id="cb43-8"><a href="#cb43-8"></a>                <span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, estimate)),</span>
<span id="cb43-9"><a href="#cb43-9"></a>            <span class="at">position =</span> <span class="fu">position_dodge2</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>),</span>
<span id="cb43-10"><a href="#cb43-10"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.75</span>) <span class="sc">+</span></span>
<span id="cb43-11"><a href="#cb43-11"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Treatment Effects"</span>, <span class="at">y =</span> <span class="st">""</span>, <span class="at">color =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb43-12"><a href="#cb43-12"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"County-Year FE"</span> <span class="ot">=</span> <span class="st">"black"</span>, </span>
<span id="cb43-13"><a href="#cb43-13"></a>                                <span class="st">"County-Year FE + Covariates"</span> <span class="ot">=</span> <span class="st">"gray50"</span>)) <span class="sc">+</span></span>
<span id="cb43-14"><a href="#cb43-14"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb43-15"><a href="#cb43-15"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Outcome, <span class="at">ncol =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb43-16"><a href="#cb43-16"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb43-17"><a href="#cb43-17"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="2700"></p>
</figure>
</div>
</div>
</div>
<p>　以上の結果から「学校内銃撃事件の発生は投票参加を促すとは言えないものの、民主党候補者の得票率を上げる」ということが言えよう。</p>
</section>
<section id="scm" class="level2">
<h2 class="anchored" data-anchor-id="scm">SCM</h2>
<p>　ここでは、差分の差分法の応用としてSynthetic Control Method（SCM）を{gsynth}パッケージの使い方に重点を起きながら説明する。Synthetic Control MethodをRに実装したパッケージは{Synth}、{gsynth}、{bpCausal}などがある。SCMの代表的な論文の一つであるAbadie et al.（2015）は{Synth}パッケージを使っているが、使い方はかなり複雑である。したがって、ここでは使い方が最も簡単な{gsynth}パッケージについて説明する<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>。</p>
<p>　ここで使用するのは歴代参院選（第7回以降）における都道府県の投票率である<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>。処置変数は第24回参院選から導入された「合区」だ。具体的には鳥取選挙区と島根選挙区が「鳥取・島根選挙区」に、徳島選挙区と高知選挙区が「徳島・高知選挙区」として合区されたか否かである。合区によって自分の1票の価値がほぼ半分に下がり、投票参加を妨げたのではないかという議論もあるが、本当だろうか。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a>scm_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/did_data6.csv"</span>)</span>
<span id="cb44-2"><a href="#cb44-2"></a></span>
<span id="cb44-3"><a href="#cb44-3"></a>scm_df</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 938 × 9
   Election PrefCode PrefName_E PrefNam…¹ Eligi…² Voters EffVote Magni…³ Candi…⁴
      &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1        7        1 Hokkaido   北海道    2903802 1.83e6 1683764       4       7
 2        7        2 Aomori     青森県     823336 5.09e5  478380       1       5
 3        7        3 Iwate      岩手県     849109 6.20e5  591977       1       3
 4        7        4 Miyagi     宮城県    1049109 6.95e5  666205       1       4
 5        7        5 Akita      秋田県     771983 5.91e5  558603       1       3
 6        7        6 Yamagata   山形県     784438 6.37e5  615414       1       3
 7        7        7 Fukushima  福島県    1123975 8.93e5  855609       2       5
 8        7        8 Ibaraki    茨城県    1246254 7.85e5  750181       2       4
 9        7        9 Tochigi    栃木県     909245 6.38e5  614249       2       6
10        7       10 Gunma      群馬県     990083 7.20e5  690448       2       6
# … with 928 more rows, and abbreviated variable names ¹​PrefName_J, ²​Eligible,
#   ³​Magnitude, ⁴​Candidates
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a>scm_df <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Eligible<span class="sc">:</span>Candidates) <span class="sc">|&gt;</span></span>
<span id="cb46-3"><a href="#cb46-3"></a>  <span class="fu">descr</span>(<span class="at">stats =</span> <span class="fu">c</span>(<span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"min"</span>, <span class="st">"max"</span>, <span class="st">"n.valid"</span>),</span>
<span id="cb46-4"><a href="#cb46-4"></a>        <span class="at">transpose =</span> <span class="cn">TRUE</span>, <span class="at">order =</span> <span class="st">"p"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Error : Can't find dplyr</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Descriptive Statistics  

                         Mean      Std.Dev         Min           Max   N.Valid
---------------- ------------ ------------ ----------- ------------- ---------
        Eligible   1933435.87   1867850.63   364184.00   11454822.00    938.00
          Voters   1139531.46   1029039.25   226580.00    6477709.00    938.00
         EffVote   1096934.10    997876.11   217637.00    6298466.00    938.00
       Magnitude         1.60         0.87        1.00          6.00    938.00
      Candidates         5.49         5.42        2.00         72.00    938.00</code></pre>
</div>
</div>
<table class="table">
<thead>
<tr class="header">
<th>変数名</th>
<th>説明</th>
<th>備考</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Election</code></td>
<td>選挙</td>
<td>第<strong>XX</strong>回参議院議員通常選挙</td>
</tr>
<tr class="even">
<td><code>PrefCode</code></td>
<td>都道府県</td>
<td>JIS規格コード</td>
</tr>
<tr class="odd">
<td><code>PrefName_E</code></td>
<td>都道府県</td>
<td>英語</td>
</tr>
<tr class="even">
<td><code>PrefName_J</code></td>
<td>都道府県</td>
<td>日本語</td>
</tr>
<tr class="odd">
<td><code>Eligible</code></td>
<td>有権者数</td>
<td></td>
</tr>
<tr class="even">
<td><code>Voters</code></td>
<td>投票者数</td>
<td></td>
</tr>
<tr class="odd">
<td><code>EffVote</code></td>
<td>有効投票数</td>
<td></td>
</tr>
<tr class="even">
<td><code>Magnitude</code></td>
<td>定数</td>
<td></td>
</tr>
<tr class="odd">
<td><code>Candidates</code></td>
<td>候補者数</td>
<td></td>
</tr>
</tbody>
</table>
<p>　合区された選挙区における定数および候補者数の扱いについてだが、たとえば島根選挙区の場合、合区前の定数は1である。合区後の鳥取・島根選挙区も定数1だ。この場合、合区後の島根「県」の定数を1にするか0.5にするか、そして候補者数も合区における候補者数にすべきか、2に割るかが問題となるが、ここでは定数を1とし、候補者数も合区における候補者数とした。このようなコーディングが実証上、正しいかどうかは分からないが、実習の段階では問題ないだろう。</p>
<p>　それでは、データを以下のように加工する。</p>
<ol type="1">
<li><code>Treat</code>という変数を作成する。<code>PrefName</code>が「鳥取県」、「島根県」、「徳島県」、「高知県」であり、<code>Election</code>が24以上なら1、それ以外のケースは0とする。</li>
<li><code>Turnout</code>という変数を作成する。投票者数（<code>Voters</code>）を有権者数（<code>Eligible</code>）で割り、100を掛ける。</li>
<li><code>Spoilt</code>という変数を作成する。有効投票数（<code>EffVote</code>）を有権者数（<code>Eligible</code>）で割った値を1から引き、100を掛ける。</li>
<li>都道府県名（<code>PrefName_E</code>）をfactor変数に変換し、<code>PrefName_F</code>という列として追加します。水準（levels）の順番はデータの出現順とする。</li>
<li>都道府県名（<code>PrefName_J</code>）をfactor化し、要素の順番は<code>scm_df</code>内における表示順番とする。</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1"></a>scm_df <span class="ot">&lt;-</span> scm_df <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="#cb49-2"></a>  <span class="fu">mutate</span>(<span class="at">Treat      =</span> <span class="fu">if_else</span>(PrefName_E <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Tottori"</span>, <span class="st">"Shimane"</span>,</span>
<span id="cb49-3"><a href="#cb49-3"></a>                                                <span class="st">"Tokushima"</span>,<span class="st">"Kochi"</span>) <span class="sc">&amp;</span></span>
<span id="cb49-4"><a href="#cb49-4"></a>                                Election <span class="sc">&gt;=</span> <span class="dv">24</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb49-5"><a href="#cb49-5"></a>         <span class="at">Turnout    =</span> Voters <span class="sc">/</span> Eligible <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb49-6"><a href="#cb49-6"></a>         <span class="at">Spoilt     =</span> (<span class="dv">1</span> <span class="sc">-</span> (EffVote <span class="sc">/</span> Voters)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb49-7"><a href="#cb49-7"></a>         <span class="at">PrefName_J =</span> <span class="fu">fct_inorder</span>(PrefName_J))</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>　本格的な分析に入る前に、各ケースの処置有無を可視化してみよう。パネルデータの確認には{panelView}パッケージの<code>panelview()</code>関数を使う。第一引数は<code>応答変数 ~ 処置変数</code>であり、<code>data</code>引数にデータフレームのオブジェクト名を指定する。また、<code>index</code>にはユニットと時間を表す変数名を長さ2のcharacter型ベクトルとして指定します。ここでは<code>"PrefName_J"</code>と<code>"Election"</code>である。最後に、<code>pre.post = TRUE</code>を指定すると、処置前後を色分けしてくれるので、見やすくなる。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a><span class="fu">panelview</span>(Turnout <span class="sc">~</span> Treat, <span class="at">data =</span> scm_df, </span>
<span id="cb50-2"><a href="#cb50-2"></a>          <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"PrefName_J"</span>, <span class="st">"Election"</span>), <span class="at">pre.post =</span> <span class="cn">TRUE</span>,</span>
<span id="cb50-3"><a href="#cb50-3"></a>          <span class="at">xlab =</span> <span class="st">"参院選"</span>, <span class="at">ylab =</span> <span class="st">"都道府県"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<p>　これを見ると処置を受けるケースが4県であり、どれも第24回参院選から処置を受けることが分かる。また、沖縄県の場合、第7・8回参院選のデータが欠損していることが分かる。</p>
<p>　次は投票率の変化を時系列的に示してみよう。使い方は先ほどとほぼ同じだが、<code>panelView()</code>内に<code>type = "outcome"</code>引数を追加する。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1"></a><span class="fu">panelview</span>(Turnout <span class="sc">~</span> Treat, <span class="at">data =</span> scm_df, </span>
<span id="cb51-2"><a href="#cb51-2"></a>          <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"PrefName_J"</span>, <span class="st">"Election"</span>), </span>
<span id="cb51-3"><a href="#cb51-3"></a>          <span class="at">type  =</span> <span class="st">"outcome"</span>,</span>
<span id="cb51-4"><a href="#cb51-4"></a>          <span class="at">main  =</span> <span class="st">"投票率の推移"</span>,</span>
<span id="cb51-5"><a href="#cb51-5"></a>          <span class="at">xlab  =</span> <span class="st">"参院選"</span>,</span>
<span id="cb51-6"><a href="#cb51-6"></a>          <span class="at">ylab  =</span> <span class="st">"投票率 (%)"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<p>　これを見ると、都道府県内における投票率の変化にはバラツキがあるが、傾向としてはかなり似通っていることが分かる。また、処置後の変化（濃い青の線）を見ると、他の都道府県よりかなり落ちているようにも見える。これは合区によって何かの変化が生じた可能性があることを示唆している。</p>
<p>　それではSCMをやってみよう。基本的な使い方は<code>lm()</code>関数に近いが、それでも必要な引数がそれなりにある。ここではその一部を紹介する。</p>
<ul>
<li>第1引数は<code>応答変数 ~ 処置変数 + 統制変数1 + 統制変数2 + ...</code>であり、統制変数は必須ではない。ここでは統制変数として定数（<code>Magnitude</code>）と候補者数（<code>Candidates</code>）を使用する。</li>
<li><code>data</code>にはデータフレームのオブジェクト名を指定する。</li>
<li><code>index</code>は<code>panelview()</code>と同じだが、<strong>一つ注意が必要</strong>です。それは、ユニットを表す変数をこれまではfactor化された<code>"PrefName_J"</code>を使ってきたが、factor化されて<strong>いない</strong><code>"PrefName_E"</code>にすることだ。まだ開発途上のパッケージということもあり、ユニット変数がfactor型だと、正しく推定できない。<code>PrefName_E</code>はfactor型でなくcharacter型ですので、問題ない（あえて<code>PrefName_E</code>をfactor化しなかったのはこのためである）。また、numeric型である<code>PrefCode</code>を指定すれば良い。。</li>
<li><code>force</code>は固定効果をユニットレベルにするか、時間レベルにするか、両方にするか、あるいはなしにするかを意味する。既定値はユニットレベル（<code>"unit"</code>）だが、ここでは両方（<code>"two-way"</code>）にする。</li>
<li><code>se</code>は標準誤差を計算するか否かであり、既定値は<code>FALSE</code>である。ここでは標準誤差も計算するために<code>TRUE</code>に指定する。標準誤差を計算しない場合、計算が早く終わる。</li>
<li><code>inference</code>は推定方法を意味し、既定値はノンパラメトリック推定（<code>"nonparametric"</code>）です。ただし、処置ケースが少ない場合、パラメトリック推定が推奨されているため、ここでは<code>"parametric"</code>を指定する。</li>
<li><code>nboots</code>は標準誤差を計算する際に使用されるブートストラッピングの回数である。既定値は200ですが、ここでは500回にする。</li>
<li><code>parallel</code>は並列計算の有無を意味する。既定値は<code>TRUE</code>で、このままでも通常は問題ない。ただし、R Markdown上で{gsynth}を使用する場合は並列計算ができないため、<code>FALSE</code>にしておく（処理時間が倍以上になる）。</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a>scm_fit <span class="ot">&lt;-</span> <span class="fu">gsynth</span>(Turnout <span class="sc">~</span> Treat <span class="sc">+</span> Magnitude <span class="sc">+</span> Candidates, </span>
<span id="cb52-2"><a href="#cb52-2"></a>                  <span class="at">data =</span> scm_df, <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"PrefName_E"</span>, <span class="st">"Election"</span>), </span>
<span id="cb52-3"><a href="#cb52-3"></a>                  <span class="at">force =</span> <span class="st">"two-way"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">inference =</span> <span class="st">"parametric"</span>,</span>
<span id="cb52-4"><a href="#cb52-4"></a>                  <span class="at">nboots =</span> <span class="dv">500</span>, <span class="at">parallel =</span> <span class="cn">TRUE</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1"></a><span class="fu">print</span>(scm_fit)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
gsynth.formula(formula = Turnout ~ Treat + Magnitude + Candidates, 
    data = scm_df, index = c("PrefName_E", "Election"), force = "two-way", 
    se = TRUE, nboots = 500, inference = "parametric", parallel = FALSE)

Average Treatment Effect on the Treated:
        Estimate  S.E. CI.lower CI.upper   p.value
ATT.avg   -6.563 1.463    -9.43   -3.696 7.242e-06

   ~ by Period (including Pre-treatment Periods):
         ATT   S.E. CI.lower CI.upper   p.value n.Treated
-16  0.09054 1.2301  -2.3205  2.50155 9.413e-01         0
-15 -0.56609 1.1603  -2.8403  1.70812 6.256e-01         0
-14  3.32790 1.0443   1.2811  5.37466 1.439e-03         0
-13  1.44804 0.9972  -0.5064  3.40244 1.465e-01         0
-12 -1.53058 1.0356  -3.5602  0.49908 1.394e-01         0
-11 -1.21442 0.8801  -2.9393  0.51048 1.676e-01         0
-10 -2.51664 1.2571  -4.9806 -0.05272 4.530e-02         0
-9  -1.69683 1.0860  -3.8253  0.43163 1.182e-01         0
-8   1.12683 0.9586  -0.7520  3.00562 2.398e-01         0
-7  -1.03078 1.0960  -3.1789  1.11730 3.470e-01         0
-6   3.60723 1.5520   0.5653  6.64915 2.011e-02         0
-5  -0.85728 1.2777  -3.3615  1.64695 5.022e-01         0
-4   0.34762 0.9497  -1.5137  2.20893 7.143e-01         0
-3  -0.38462 0.9695  -2.2848  1.51553 6.916e-01         0
-2   0.26204 0.9226  -1.5463  2.07033 7.764e-01         0
-1   1.56199 0.8999  -0.2017  3.32571 8.260e-02         0
0   -1.97495 0.9112  -3.7608 -0.18913 3.019e-02         0
1   -6.57256 1.4040  -9.3243 -3.82083 2.849e-06         4
2   -6.87683 2.0956 -10.9841 -2.76959 1.032e-03         4
3   -6.24002 1.7173  -9.6059 -2.87413 2.795e-04         4

Coefficients for the Covariates:
               beta    S.E. CI.lower CI.upper   p.value
Magnitude   2.64853 0.79438   1.0916   4.2055 0.0008558
Candidates -0.05892 0.03945  -0.1362   0.0184 0.1353069</code></pre>
</div>
</div>
<p>　平均値な処置効果（AT<strong>T</strong>）は-6.563であり、統計的にも有意な結果が得られた。これは合区が行われた選挙区は、もし合区しなかった場合の投票率に比べ、約-6.563%p低いことを意味します。また、<code>~ by Period</code>以下の欄では各選挙ごとのAT<strong>T</strong>が表示されます。1以降が合区以降の時期であり、それぞれ約-6.573%p、-6.877%p、-6.240%pである。上記の-6.563はこの3つの数値の平均値である。ちなみに処置群の県が4つにも関わらず、AT<strong>T</strong>が一つだけ表示されるのは、4つの平均値を出しているからだ。それぞれの県ごとに効果を確認する方法は後ほど解説する。とりあえず、この結果から合区は投票率を下げたという解釈ができよう。</p>
<p>　以上の結果を可視化するためには<code>plot()</code>関数を使う。タイトル、横軸、縦軸のラベルは<code>main</code>、<code>xlab</code>、<code>ylab</code>で指定できる。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1"></a><span class="fu">plot</span>(scm_fit, </span>
<span id="cb55-2"><a href="#cb55-2"></a>     <span class="at">main =</span> <span class="st">"Estimated ATT"</span>, </span>
<span id="cb55-3"><a href="#cb55-3"></a>     <span class="at">xlab =</span> <span class="st">"Election (0 = 2013 Election)"</span>, </span>
<span id="cb55-4"><a href="#cb55-4"></a>     <span class="at">ylab =</span> <span class="st">"ATT (%p)"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>　処置を受ける<strong>前</strong>は架空の4県とその実際の4県の間に投票率の差はあまりなかったが、処置を受けてから差が広がることが分かる。差分でなく、合成された架空の4県と実際の4県のトレンドを見るためには<code>type = "counterfactual"</code>、もしくは<code>type = "ct"</code>を指定します。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a><span class="fu">plot</span>(scm_fit, </span>
<span id="cb56-2"><a href="#cb56-2"></a>     <span class="at">type =</span> <span class="st">"counterfactual"</span>, </span>
<span id="cb56-3"><a href="#cb56-3"></a>     <span class="at">main =</span> <span class="st">""</span>,</span>
<span id="cb56-4"><a href="#cb56-4"></a>     <span class="at">xlab =</span> <span class="st">"Election"</span>, </span>
<span id="cb56-5"><a href="#cb56-5"></a>     <span class="at">ylab =</span> <span class="st">"Turnout (%)"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>　処置を受けたのは4県であるが、線が1本になっている。ここからも処置前は架空の4県と実際の4県はほぼ同じトレンドを示していますが、処置後は傾向が変わったことが確認できる。</p>
<p>　もし、4つの都道府県を個別に示したい場合はどうすれば良いだろうか。この場合、<code>plot()</code>内に<code>id</code>引数を使えば良い。たとえば、鳥取県の処置効果（ATT）を確認するためには<code>id = "Tottori"</code>と指定する。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1"></a><span class="fu">plot</span>(scm_fit, <span class="at">id =</span> <span class="st">"Tottori"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1"></a><span class="fu">plot</span>(scm_fit, <span class="at">id =</span> <span class="st">"Tottori"</span>, <span class="at">type =</span> <span class="st">"ct"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>　4つの都道府県のデータを個別のファセットで全て出すためにはゼロベースで作図した方が効率的かも知れない。また、この場合は図のカスタマイズの幅も広がる。{gsynth}から得られたオブジェクトには架空の鳥取、島根、徳島、高知のデータが個別に格納されているため、それを抽出すれば個別の図を作成することもできる。たとえば、処置群（4県）の観察済みのデータは<code>オブジェクト名$Y.tr</code>で抽出できる。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a>scm_fit<span class="sc">$</span>Y.tr</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Kochi  Shimane Tokushima  Tottori
7  74.63966 83.49050  69.39499 81.24437
8  75.69312 84.78405  69.88441 83.69962
9  71.37616 78.14244  63.66989 77.03502
10 75.69410 86.92480  78.45754 84.82852
11 70.90031 85.15588  63.40844 83.37384
12 72.83410 87.58638  77.05070 84.86225
13 61.27247 75.36695  49.81165 74.79201
14 72.01185 86.89197  70.26960 85.81677
15 70.52034 82.31831  65.59127 78.71451
16 54.89730 73.79272  48.42299 67.28538
17 50.63857 67.09330  47.14380 67.57092
18 56.21296 73.26601  56.91326 70.03591
19 58.38653 68.61257  57.24322 66.68463
20 57.29701 68.87462  54.59808 64.16773
21 58.39998 71.80893  58.46591 67.67363
22 58.49266 71.70006  58.23675 65.76520
23 49.88987 60.89257  49.29437 58.87696
24 45.51522 62.19714  46.97798 56.28266
25 46.34053 54.04000  38.59305 49.97934
26 47.36311 56.37101  45.72428 48.92585</code></pre>
</div>
</div>
<p>　このデータは行列構造となっているため、<code>as_tibble()</code>で表形式へ変更し、<code>treat_df</code>という名で格納する。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1"></a>treat_df <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(scm_fit<span class="sc">$</span>Y.tr)</span>
<span id="cb61-2"><a href="#cb61-2"></a></span>
<span id="cb61-3"><a href="#cb61-3"></a>treat_df</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 4
   Kochi Shimane Tokushima Tottori
   &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
 1  74.6    83.5      69.4    81.2
 2  75.7    84.8      69.9    83.7
 3  71.4    78.1      63.7    77.0
 4  75.7    86.9      78.5    84.8
 5  70.9    85.2      63.4    83.4
 6  72.8    87.6      77.1    84.9
 7  61.3    75.4      49.8    74.8
 8  72.0    86.9      70.3    85.8
 9  70.5    82.3      65.6    78.7
10  54.9    73.8      48.4    67.3
11  50.6    67.1      47.1    67.6
12  56.2    73.3      56.9    70.0
13  58.4    68.6      57.2    66.7
14  57.3    68.9      54.6    64.2
15  58.4    71.8      58.5    67.7
16  58.5    71.7      58.2    65.8
17  49.9    60.9      49.3    58.9
18  45.5    62.2      47.0    56.3
19  46.3    54.0      38.6    50.0
20  47.4    56.4      45.7    48.9</code></pre>
</div>
</div>
<p>　この<code>treat_df</code>だけは各投票率がいつの投票率かが分からない。<code>Election</code>列を<code>Kochi</code>列前に追加し（<code>mutate()</code>内の最後に<code>.before = Kochi</code>を指定すると、<code>mutate()</code>で生成・修正された列が<code>Kochi</code>列の前へ移動する）、7から26までを入れる。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1"></a>treat_df <span class="ot">&lt;-</span> treat_df <span class="sc">|&gt;</span></span>
<span id="cb63-2"><a href="#cb63-2"></a>  <span class="fu">mutate</span>(<span class="at">Election =</span> <span class="dv">7</span><span class="sc">:</span><span class="dv">26</span>, <span class="at">.before =</span> Kochi)</span>
<span id="cb63-3"><a href="#cb63-3"></a></span>
<span id="cb63-4"><a href="#cb63-4"></a>treat_df</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 5
   Election Kochi Shimane Tokushima Tottori
      &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
 1        7  74.6    83.5      69.4    81.2
 2        8  75.7    84.8      69.9    83.7
 3        9  71.4    78.1      63.7    77.0
 4       10  75.7    86.9      78.5    84.8
 5       11  70.9    85.2      63.4    83.4
 6       12  72.8    87.6      77.1    84.9
 7       13  61.3    75.4      49.8    74.8
 8       14  72.0    86.9      70.3    85.8
 9       15  70.5    82.3      65.6    78.7
10       16  54.9    73.8      48.4    67.3
11       17  50.6    67.1      47.1    67.6
12       18  56.2    73.3      56.9    70.0
13       19  58.4    68.6      57.2    66.7
14       20  57.3    68.9      54.6    64.2
15       21  58.4    71.8      58.5    67.7
16       22  58.5    71.7      58.2    65.8
17       23  49.9    60.9      49.3    58.9
18       24  45.5    62.2      47.0    56.3
19       25  46.3    54.0      38.6    50.0
20       26  47.4    56.4      45.7    48.9</code></pre>
</div>
</div>
<p>　続いて、{tidyr}の<code>pivot_longer()</code>関数を使って<code>treat_df</code>をlong型データへ変換する。<code>pivot_*()</code>関数の使い方については『私たちのR』<a href="https://www.jaysong.net/RBook/tidydata.html">第15章「整然データ構造」</a>を参照されたい。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1"></a>treat_df <span class="ot">&lt;-</span> treat_df <span class="sc">|&gt;</span></span>
<span id="cb65-2"><a href="#cb65-2"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols      =</span> Kochi<span class="sc">:</span>Tottori,</span>
<span id="cb65-3"><a href="#cb65-3"></a>               <span class="at">names_to  =</span> <span class="st">"Pref"</span>,</span>
<span id="cb65-4"><a href="#cb65-4"></a>               <span class="at">values_to =</span> <span class="st">"Turnout"</span>)</span>
<span id="cb65-5"><a href="#cb65-5"></a></span>
<span id="cb65-6"><a href="#cb65-6"></a>treat_df</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 80 × 3
   Election Pref      Turnout
      &lt;int&gt; &lt;chr&gt;       &lt;dbl&gt;
 1        7 Kochi        74.6
 2        7 Shimane      83.5
 3        7 Tokushima    69.4
 4        7 Tottori      81.2
 5        8 Kochi        75.7
 6        8 Shimane      84.8
 7        8 Tokushima    69.9
 8        8 Tottori      83.7
 9        9 Kochi        71.4
10        9 Shimane      78.1
# … with 70 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>　同じ作業を架空の処置群についても行う。架空の処置群は<code>オブジェクト名$Y.ct</code>で抽出できる。今回は全ての作業をパイプ演算子で繋ぎ、コードを効率化する。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1"></a>counter_df <span class="ot">&lt;-</span> scm_fit<span class="sc">$</span>Y.ct <span class="sc">|&gt;</span></span>
<span id="cb67-2"><a href="#cb67-2"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb67-3"><a href="#cb67-3"></a>  <span class="fu">mutate</span>(<span class="at">Election =</span> <span class="dv">7</span><span class="sc">:</span><span class="dv">26</span>, <span class="at">.before =</span> Kochi) <span class="sc">|&gt;</span></span>
<span id="cb67-4"><a href="#cb67-4"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols      =</span> Kochi<span class="sc">:</span>Tottori,</span>
<span id="cb67-5"><a href="#cb67-5"></a>               <span class="at">names_to  =</span> <span class="st">"Pref"</span>,</span>
<span id="cb67-6"><a href="#cb67-6"></a>               <span class="at">values_to =</span> <span class="st">"Turnout"</span>)</span>
<span id="cb67-7"><a href="#cb67-7"></a></span>
<span id="cb67-8"><a href="#cb67-8"></a>counter_df</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 80 × 3
   Election Pref      Turnout
      &lt;int&gt; &lt;chr&gt;       &lt;dbl&gt;
 1        7 Kochi        73.5
 2        7 Shimane      84.0
 3        7 Tokushima    67.6
 4        7 Tottori      83.3
 5        8 Kochi        75.3
 6        8 Shimane      85.7
 7        8 Tokushima    70.7
 8        8 Tottori      84.7
 9        9 Kochi        65.6
10        9 Shimane      76.1
# … with 70 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>　最後に<code>treat_df</code>と<code>counter_df</code>を結合する。<code>treat_df</code>の行なら<code>"観測値"</code>の値が、<code>counter_df</code>の行なら<code>"反実仮想"</code>の値が付けられた<code>Type</code>という列を追加し、この<code>Type</code>列をfactor化する。要素の順番は<code>"反実仮想"</code>、<code>"観測値"</code>の順とする。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1"></a>tr_ct_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">list</span>(<span class="st">"観測値"</span>   <span class="ot">=</span> treat_df, </span>
<span id="cb69-2"><a href="#cb69-2"></a>                           <span class="st">"反実仮想"</span> <span class="ot">=</span> counter_df),</span>
<span id="cb69-3"><a href="#cb69-3"></a>                      <span class="at">.id =</span> <span class="st">"Type"</span>) <span class="sc">|&gt;</span></span>
<span id="cb69-4"><a href="#cb69-4"></a>  <span class="fu">mutate</span>(<span class="at">Type =</span> <span class="fu">factor</span>(Type, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"反実仮想"</span>, <span class="st">"観測値"</span>)))</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>　データが揃ったので{ggplot2}を使って折れ線グラフを作ってみよう。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1"></a>tr_ct_df <span class="sc">|&gt;</span></span>
<span id="cb70-2"><a href="#cb70-2"></a>  <span class="co"># Pref列をリコーディング &amp; factor化</span></span>
<span id="cb70-3"><a href="#cb70-3"></a>  <span class="fu">mutate</span>(<span class="at">Pref =</span> <span class="fu">recode</span>(Pref,</span>
<span id="cb70-4"><a href="#cb70-4"></a>                       <span class="st">"Tottori"</span>   <span class="ot">=</span> <span class="st">"鳥取"</span>,</span>
<span id="cb70-5"><a href="#cb70-5"></a>                       <span class="st">"Shimane"</span>   <span class="ot">=</span> <span class="st">"島根"</span>,</span>
<span id="cb70-6"><a href="#cb70-6"></a>                       <span class="st">"Tokushima"</span> <span class="ot">=</span> <span class="st">"徳島"</span>,</span>
<span id="cb70-7"><a href="#cb70-7"></a>                       <span class="st">"Kochi"</span>     <span class="ot">=</span> <span class="st">"高知"</span>),</span>
<span id="cb70-8"><a href="#cb70-8"></a>         <span class="at">Pref =</span> <span class="fu">factor</span>(Pref, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"鳥取"</span>, <span class="st">"島根"</span>, <span class="st">"徳島"</span>, <span class="st">"高知"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb70-9"><a href="#cb70-9"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb70-10"><a href="#cb70-10"></a>  <span class="co"># x = 23の箇所に垂直線の破線を引く</span></span>
<span id="cb70-11"><a href="#cb70-11"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">23</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb70-12"><a href="#cb70-12"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> Election, <span class="at">y =</span> Turnout, <span class="at">linetype =</span> Type, <span class="at">color =</span> Type),</span>
<span id="cb70-13"><a href="#cb70-13"></a>            <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb70-14"><a href="#cb70-14"></a>  <span class="co"># 線の色</span></span>
<span id="cb70-15"><a href="#cb70-15"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"観測値"</span>   <span class="ot">=</span> <span class="st">"black"</span>, </span>
<span id="cb70-16"><a href="#cb70-16"></a>                                <span class="st">"反実仮想"</span> <span class="ot">=</span> <span class="st">"orange"</span>)) <span class="sc">+</span></span>
<span id="cb70-17"><a href="#cb70-17"></a>  <span class="co"># 線のタイプ（1 = 実線; 2 = 破線）</span></span>
<span id="cb70-18"><a href="#cb70-18"></a>  <span class="fu">scale_linetype_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"観測値"</span>   <span class="ot">=</span> <span class="dv">1</span>, </span>
<span id="cb70-19"><a href="#cb70-19"></a>                                   <span class="st">"反実仮想"</span> <span class="ot">=</span> <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb70-20"><a href="#cb70-20"></a>  <span class="co"># colorの凡例は残し、linetypeの凡例は無くす</span></span>
<span id="cb70-21"><a href="#cb70-21"></a>  <span class="fu">guides</span>(<span class="at">linetype =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb70-22"><a href="#cb70-22"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"選挙"</span>, <span class="at">y =</span> <span class="st">"投票率 (%)"</span>, <span class="at">color =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb70-23"><a href="#cb70-23"></a>  <span class="co"># 都道府県ごとにファセット分割</span></span>
<span id="cb70-24"><a href="#cb70-24"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Pref, <span class="at">ncol =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb70-25"><a href="#cb70-25"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb70-26"><a href="#cb70-26"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<p>　ただし、この図だけだと処置効果（ATT）が分かりにくい。処置効果は観測値（=処置群）と反実仮想（=架空の統制群）の差分である。<code>tr_ct_df</code>からもATTの計算はできるが、ATTの不確実性（標準誤差や信頼区間など）までは分からない。処置効果（ATT）を抽出は<code>オブジェクト名$est.ind</code>で出来るが、3次元配列（array構造）になっているため、<code>オブジェクト名$est.ind[, , "処置群名"]</code>で抽出する必要がある。処置群名は今回の場合だと<code>PrefName_E</code>上の名前である。たとえば、鳥取における処置効果は以下のように抽出する。これらもまた表形式でなく、行列構造であるので、<code>as_tibble()</code>を使って表形式にしよう。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1"></a><span class="fu">as_tibble</span>(scm_fit<span class="sc">$</span>est.ind[, , <span class="st">"Tottori"</span>])</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 5
        Eff  S.E. CI.lower CI.upper  p.value
      &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
 1  -2.03    2.33  -6.59       2.53 0.382   
 2  -0.960   2.13  -5.14       3.22 0.653   
 3   1.69    2.07  -2.36       5.74 0.415   
 4   1.07    2.01  -2.87       5.00 0.596   
 5   0.721   2.00  -3.21       4.65 0.719   
 6  -0.704   1.74  -4.11       2.71 0.686   
 7  -0.926   2.33  -5.49       3.63 0.691   
 8   0.816   2.08  -3.27       4.90 0.695   
 9   0.247   1.90  -3.48       3.98 0.897   
10  -3.24    2.23  -7.61       1.13 0.147   
11   5.88    3.03  -0.0512    11.8  0.0520  
12   0.143   2.28  -4.33       4.61 0.950   
13   0.0189  1.89  -3.69       3.73 0.992   
14  -1.48    1.77  -4.94       1.98 0.401   
15  -0.0566  1.83  -3.65       3.53 0.975   
16   0.456   1.79  -3.06       3.97 0.799   
17  -1.63    1.76  -5.07       1.81 0.353   
18  -6.90    2.86 -12.5       -1.30 0.0157  
19  -9.00    3.94 -16.7       -1.28 0.0223  
20 -10.9     3.23 -17.2       -4.56 0.000750</code></pre>
</div>
</div>
<p>　ここで<code>Eff</code>列が架空の鳥取と実際の鳥取の差、つまり処置効果である。そして、<code>CI.lower</code>と<code>CI.upper</code>がそれぞれ95%信頼区間の下限と上限だ。これら4つの県のデータを結合し、<code>Election</code>変数を追加、都道府県をfactor化したものを<code>att_df</code>という名で格納する。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1"></a>att_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">list</span>(<span class="st">"鳥取"</span> <span class="ot">=</span> <span class="fu">as_tibble</span>(scm_fit<span class="sc">$</span>est.ind[, , <span class="st">"Tottori"</span>]),</span>
<span id="cb73-2"><a href="#cb73-2"></a>                         <span class="st">"島根"</span> <span class="ot">=</span> <span class="fu">as_tibble</span>(scm_fit<span class="sc">$</span>est.ind[, , <span class="st">"Shimane"</span>]),</span>
<span id="cb73-3"><a href="#cb73-3"></a>                         <span class="st">"徳島"</span> <span class="ot">=</span> <span class="fu">as_tibble</span>(scm_fit<span class="sc">$</span>est.ind[, , <span class="st">"Tokushima"</span>]),</span>
<span id="cb73-4"><a href="#cb73-4"></a>                         <span class="st">"高知"</span> <span class="ot">=</span> <span class="fu">as_tibble</span>(scm_fit<span class="sc">$</span>est.ind[, , <span class="st">"Kochi"</span>])),</span>
<span id="cb73-5"><a href="#cb73-5"></a>                    <span class="at">.id =</span> <span class="st">"Pref"</span>) <span class="sc">|&gt;</span></span>
<span id="cb73-6"><a href="#cb73-6"></a>  <span class="fu">mutate</span>(<span class="at">Election =</span> <span class="fu">rep</span>(<span class="dv">7</span><span class="sc">:</span><span class="dv">26</span>, <span class="dv">4</span>), <span class="co"># 7~26を4回繰り返し</span></span>
<span id="cb73-7"><a href="#cb73-7"></a>         <span class="at">.before =</span> Pref) <span class="sc">|&gt;</span>       <span class="co"># Election列をPref列の前に</span></span>
<span id="cb73-8"><a href="#cb73-8"></a>  <span class="fu">mutate</span>(<span class="at">Pref =</span> <span class="fu">fct_inorder</span>(Pref))</span>
<span id="cb73-9"><a href="#cb73-9"></a></span>
<span id="cb73-10"><a href="#cb73-10"></a>att_df</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 80 × 7
   Election Pref     Eff  S.E. CI.lower CI.upper p.value
      &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
 1        7 鳥取  -2.03   2.33    -6.59     2.53   0.382
 2        8 鳥取  -0.960  2.13    -5.14     3.22   0.653
 3        9 鳥取   1.69   2.07    -2.36     5.74   0.415
 4       10 鳥取   1.07   2.01    -2.87     5.00   0.596
 5       11 鳥取   0.721  2.00    -3.21     4.65   0.719
 6       12 鳥取  -0.704  1.74    -4.11     2.71   0.686
 7       13 鳥取  -0.926  2.33    -5.49     3.63   0.691
 8       14 鳥取   0.816  2.08    -3.27     4.90   0.695
 9       15 鳥取   0.247  1.90    -3.48     3.98   0.897
10       16 鳥取  -3.24   2.23    -7.61     1.13   0.147
# … with 70 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>　それでは折れ線グラフを作ってみよう。ただし、今回は点推定値（折れ線グラフ）だけでなく、信頼区間も示す必要があるので<code>geom_ribbon()</code>レイヤーを追加する。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1"></a>att_df <span class="sc">|&gt;</span></span>
<span id="cb75-2"><a href="#cb75-2"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb75-3"><a href="#cb75-3"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb75-4"><a href="#cb75-4"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">23</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb75-5"><a href="#cb75-5"></a>  <span class="co"># 信頼区間</span></span>
<span id="cb75-6"><a href="#cb75-6"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> Election, <span class="at">ymin =</span> CI.lower, <span class="at">ymax =</span> CI.upper),</span>
<span id="cb75-7"><a href="#cb75-7"></a>              <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb75-8"><a href="#cb75-8"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> Election, <span class="at">y =</span> Eff)) <span class="sc">+</span></span>
<span id="cb75-9"><a href="#cb75-9"></a>  <span class="co"># 以下のgeom_point()なあってもなくても良い</span></span>
<span id="cb75-10"><a href="#cb75-10"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> Election, <span class="at">y =</span> Eff), </span>
<span id="cb75-11"><a href="#cb75-11"></a>             <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">fill =</span> <span class="st">"black"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb75-12"><a href="#cb75-12"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Election"</span>, <span class="at">y =</span> <span class="st">"Gap (%p)"</span>) <span class="sc">+</span></span>
<span id="cb75-13"><a href="#cb75-13"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Pref, <span class="at">ncol =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb75-14"><a href="#cb75-14"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb75-15"><a href="#cb75-15"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<p>　個別に見ると、合区直後、合区によって投票率を下がったのは鳥取、徳島、高知である。しかし、合区から3回目の選挙となる2022年（第26回）では鳥取のみとなる。</p>
<p>　SCMは統制群から合成された架空の鳥取、島根、徳島、高知を作成し、こちらを実際の統制群として用いる手法である。その際に43都道府県を重み付け合成されるが、それぞれの重みはいくつだろうか。<code>gsynth()</code>から得られたオブジェクトから<code>wgt.implied</code>を抽出すればその重みが分かる。通常のSCMの場合、重みは正の値であるが、一般化SCMの場合は負も正もあり得る。</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1"></a>scm_fit<span class="sc">$</span>wgt.implied</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="bsnmkcqnry" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#bsnmkcqnry .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#bsnmkcqnry .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bsnmkcqnry .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#bsnmkcqnry .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#bsnmkcqnry .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bsnmkcqnry .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bsnmkcqnry .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#bsnmkcqnry .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#bsnmkcqnry .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#bsnmkcqnry .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#bsnmkcqnry .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#bsnmkcqnry .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#bsnmkcqnry .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#bsnmkcqnry .gt_from_md > :first-child {
  margin-top: 0;
}

#bsnmkcqnry .gt_from_md > :last-child {
  margin-bottom: 0;
}

#bsnmkcqnry .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#bsnmkcqnry .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#bsnmkcqnry .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#bsnmkcqnry .gt_row_group_first td {
  border-top-width: 2px;
}

#bsnmkcqnry .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bsnmkcqnry .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#bsnmkcqnry .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#bsnmkcqnry .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bsnmkcqnry .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bsnmkcqnry .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#bsnmkcqnry .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#bsnmkcqnry .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bsnmkcqnry .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bsnmkcqnry .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bsnmkcqnry .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bsnmkcqnry .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bsnmkcqnry .gt_left {
  text-align: left;
}

#bsnmkcqnry .gt_center {
  text-align: center;
}

#bsnmkcqnry .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#bsnmkcqnry .gt_font_normal {
  font-weight: normal;
}

#bsnmkcqnry .gt_font_bold {
  font-weight: bold;
}

#bsnmkcqnry .gt_font_italic {
  font-style: italic;
}

#bsnmkcqnry .gt_super {
  font-size: 65%;
}

#bsnmkcqnry .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#bsnmkcqnry .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#bsnmkcqnry .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#bsnmkcqnry .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#bsnmkcqnry .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#bsnmkcqnry .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Kochi</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Shimane</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Tokushima</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Tottori</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right gt_stub">Aichi</td>
<td class="gt_row gt_right">0.022</td>
<td class="gt_row gt_right">−2.169</td>
<td class="gt_row gt_right">−2.755</td>
<td class="gt_row gt_right">0.448</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Akita</td>
<td class="gt_row gt_right">−0.151</td>
<td class="gt_row gt_right">−0.161</td>
<td class="gt_row gt_right">−0.798</td>
<td class="gt_row gt_right">0.170</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Aomori</td>
<td class="gt_row gt_right">−0.069</td>
<td class="gt_row gt_right">−1.188</td>
<td class="gt_row gt_right">−1.613</td>
<td class="gt_row gt_right">0.225</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Chiba</td>
<td class="gt_row gt_right">0.309</td>
<td class="gt_row gt_right">−2.096</td>
<td class="gt_row gt_right">−1.885</td>
<td class="gt_row gt_right">0.327</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Ehime</td>
<td class="gt_row gt_right">0.238</td>
<td class="gt_row gt_right">0.471</td>
<td class="gt_row gt_right">0.851</td>
<td class="gt_row gt_right">−0.009</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Fukui</td>
<td class="gt_row gt_right">−0.630</td>
<td class="gt_row gt_right">4.081</td>
<td class="gt_row gt_right">4.711</td>
<td class="gt_row gt_right">−1.122</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Fukuoka</td>
<td class="gt_row gt_right">−0.541</td>
<td class="gt_row gt_right">0.634</td>
<td class="gt_row gt_right">0.342</td>
<td class="gt_row gt_right">−0.368</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Fukushima</td>
<td class="gt_row gt_right">0.947</td>
<td class="gt_row gt_right">−0.235</td>
<td class="gt_row gt_right">0.669</td>
<td class="gt_row gt_right">0.402</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Gifu</td>
<td class="gt_row gt_right">0.354</td>
<td class="gt_row gt_right">0.149</td>
<td class="gt_row gt_right">0.566</td>
<td class="gt_row gt_right">0.097</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Gunma</td>
<td class="gt_row gt_right">0.318</td>
<td class="gt_row gt_right">2.085</td>
<td class="gt_row gt_right">2.968</td>
<td class="gt_row gt_right">−0.291</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Hiroshima</td>
<td class="gt_row gt_right">−0.254</td>
<td class="gt_row gt_right">1.622</td>
<td class="gt_row gt_right">2.146</td>
<td class="gt_row gt_right">−0.570</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Hokkaido</td>
<td class="gt_row gt_right">−0.553</td>
<td class="gt_row gt_right">−3.254</td>
<td class="gt_row gt_right">−5.161</td>
<td class="gt_row gt_right">0.643</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Hyogo</td>
<td class="gt_row gt_right">0.117</td>
<td class="gt_row gt_right">−3.045</td>
<td class="gt_row gt_right">−3.918</td>
<td class="gt_row gt_right">0.723</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Ibaraki</td>
<td class="gt_row gt_right">0.378</td>
<td class="gt_row gt_right">−0.483</td>
<td class="gt_row gt_right">0.902</td>
<td class="gt_row gt_right">−0.263</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Ishikawa</td>
<td class="gt_row gt_right">−0.480</td>
<td class="gt_row gt_right">1.476</td>
<td class="gt_row gt_right">1.294</td>
<td class="gt_row gt_right">−0.432</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Iwate</td>
<td class="gt_row gt_right">0.006</td>
<td class="gt_row gt_right">−2.615</td>
<td class="gt_row gt_right">−4.020</td>
<td class="gt_row gt_right">0.833</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Kagawa</td>
<td class="gt_row gt_right">−0.391</td>
<td class="gt_row gt_right">3.227</td>
<td class="gt_row gt_right">3.960</td>
<td class="gt_row gt_right">−0.902</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Kagoshima</td>
<td class="gt_row gt_right">0.098</td>
<td class="gt_row gt_right">0.202</td>
<td class="gt_row gt_right">−0.102</td>
<td class="gt_row gt_right">0.200</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Kanagawa</td>
<td class="gt_row gt_right">0.506</td>
<td class="gt_row gt_right">−3.426</td>
<td class="gt_row gt_right">−3.741</td>
<td class="gt_row gt_right">0.828</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Kumamoto</td>
<td class="gt_row gt_right">−0.791</td>
<td class="gt_row gt_right">1.767</td>
<td class="gt_row gt_right">1.083</td>
<td class="gt_row gt_right">−0.490</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Kyoto</td>
<td class="gt_row gt_right">0.397</td>
<td class="gt_row gt_right">−4.141</td>
<td class="gt_row gt_right">−5.373</td>
<td class="gt_row gt_right">1.200</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Mie</td>
<td class="gt_row gt_right">0.016</td>
<td class="gt_row gt_right">−1.162</td>
<td class="gt_row gt_right">−1.447</td>
<td class="gt_row gt_right">0.231</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Miyagi</td>
<td class="gt_row gt_right">0.712</td>
<td class="gt_row gt_right">−0.122</td>
<td class="gt_row gt_right">1.072</td>
<td class="gt_row gt_right">0.070</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Miyazaki</td>
<td class="gt_row gt_right">−1.071</td>
<td class="gt_row gt_right">5.630</td>
<td class="gt_row gt_right">6.465</td>
<td class="gt_row gt_right">−1.699</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Nagano</td>
<td class="gt_row gt_right">0.498</td>
<td class="gt_row gt_right">−1.419</td>
<td class="gt_row gt_right">−1.244</td>
<td class="gt_row gt_right">0.446</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Nagasaki</td>
<td class="gt_row gt_right">−0.921</td>
<td class="gt_row gt_right">1.910</td>
<td class="gt_row gt_right">1.572</td>
<td class="gt_row gt_right">−0.763</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Nara</td>
<td class="gt_row gt_right">0.378</td>
<td class="gt_row gt_right">−2.473</td>
<td class="gt_row gt_right">−2.658</td>
<td class="gt_row gt_right">0.589</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Nigata</td>
<td class="gt_row gt_right">0.856</td>
<td class="gt_row gt_right">−2.080</td>
<td class="gt_row gt_right">−1.318</td>
<td class="gt_row gt_right">0.535</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Oita</td>
<td class="gt_row gt_right">−0.593</td>
<td class="gt_row gt_right">2.253</td>
<td class="gt_row gt_right">1.749</td>
<td class="gt_row gt_right">−0.444</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Okayama</td>
<td class="gt_row gt_right">−0.264</td>
<td class="gt_row gt_right">0.966</td>
<td class="gt_row gt_right">1.560</td>
<td class="gt_row gt_right">−0.557</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Okinawa</td>
<td class="gt_row gt_right">0.958</td>
<td class="gt_row gt_right">0.416</td>
<td class="gt_row gt_right">0.697</td>
<td class="gt_row gt_right">0.637</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Osaka</td>
<td class="gt_row gt_right">0.387</td>
<td class="gt_row gt_right">−3.404</td>
<td class="gt_row gt_right">−4.601</td>
<td class="gt_row gt_right">1.118</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Saga</td>
<td class="gt_row gt_right">−0.913</td>
<td class="gt_row gt_right">4.668</td>
<td class="gt_row gt_right">5.637</td>
<td class="gt_row gt_right">−1.552</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Saitama</td>
<td class="gt_row gt_right">0.217</td>
<td class="gt_row gt_right">−0.975</td>
<td class="gt_row gt_right">−0.328</td>
<td class="gt_row gt_right">−0.031</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Shiga</td>
<td class="gt_row gt_right">−0.012</td>
<td class="gt_row gt_right">−0.073</td>
<td class="gt_row gt_right">−0.613</td>
<td class="gt_row gt_right">0.235</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Shizuoka</td>
<td class="gt_row gt_right">0.599</td>
<td class="gt_row gt_right">0.961</td>
<td class="gt_row gt_right">2.654</td>
<td class="gt_row gt_right">−0.330</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Tochigi</td>
<td class="gt_row gt_right">0.409</td>
<td class="gt_row gt_right">0.338</td>
<td class="gt_row gt_right">1.366</td>
<td class="gt_row gt_right">−0.143</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Tokyo</td>
<td class="gt_row gt_right">0.619</td>
<td class="gt_row gt_right">−4.424</td>
<td class="gt_row gt_right">−5.420</td>
<td class="gt_row gt_right">1.301</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Toyama</td>
<td class="gt_row gt_right">−0.819</td>
<td class="gt_row gt_right">4.384</td>
<td class="gt_row gt_right">5.389</td>
<td class="gt_row gt_right">−1.467</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Wakayama</td>
<td class="gt_row gt_right">−0.050</td>
<td class="gt_row gt_right">−1.103</td>
<td class="gt_row gt_right">−1.730</td>
<td class="gt_row gt_right">0.323</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Yamagata</td>
<td class="gt_row gt_right">0.652</td>
<td class="gt_row gt_right">−1.077</td>
<td class="gt_row gt_right">−0.815</td>
<td class="gt_row gt_right">0.508</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Yamaguchi</td>
<td class="gt_row gt_right">−1.048</td>
<td class="gt_row gt_right">1.821</td>
<td class="gt_row gt_right">0.402</td>
<td class="gt_row gt_right">−0.382</td></tr>
    <tr><td class="gt_row gt_right gt_stub">Yamanashi</td>
<td class="gt_row gt_right">−0.444</td>
<td class="gt_row gt_right">2.064</td>
<td class="gt_row gt_right">1.486</td>
<td class="gt_row gt_right">−0.274</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</section>
<section id="causalimpact" class="level2">
<h2 class="anchored" data-anchor-id="causalimpact">CausalImpact</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1"></a>ci_df <span class="ot">&lt;-</span> scm_df <span class="sc">|&gt;</span></span>
<span id="cb77-2"><a href="#cb77-2"></a>  <span class="co"># 第7・8回参院選の場合、沖縄県が欠損しているため、除外</span></span>
<span id="cb77-3"><a href="#cb77-3"></a>  <span class="fu">filter</span>(Election <span class="sc">&gt;=</span> <span class="dv">9</span>) <span class="sc">|&gt;</span></span>
<span id="cb77-4"><a href="#cb77-4"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Election, PrefName_E, Turnout)</span>
<span id="cb77-5"><a href="#cb77-5"></a></span>
<span id="cb77-6"><a href="#cb77-6"></a>ci_df</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 846 × 3
   Election PrefName_E Turnout
      &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt;
 1        9 Hokkaido      59.7
 2        9 Aomori        53.0
 3        9 Iwate         61.4
 4        9 Miyagi        60.9
 5        9 Akita         67.7
 6        9 Yamagata      70.0
 7        9 Fukushima     74.0
 8        9 Ibaraki       56.5
 9        9 Tochigi       62.0
10        9 Gunma         69.7
# … with 836 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1"></a>ci_df <span class="ot">&lt;-</span> ci_df <span class="sc">|&gt;</span> </span>
<span id="cb79-2"><a href="#cb79-2"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from  =</span> PrefName_E,</span>
<span id="cb79-3"><a href="#cb79-3"></a>              <span class="at">values_from =</span> Turnout)</span>
<span id="cb79-4"><a href="#cb79-4"></a></span>
<span id="cb79-5"><a href="#cb79-5"></a>ci_df</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 48
   Election Hokkaido Aomori Iwate Miyagi Akita Yamagata Fukush…¹ Ibaraki Tochigi
      &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1        9     59.7   53.0  61.4   60.9  67.7     70.0     74.0    56.5    62.0
 2       10     75.9   64.4  74.2   72.8  78.0     83.5     84.0    72.2    76.0
 3       11     73.7   66.1  71.9   71.4  77.4     79.9     75.2    62.5    70.2
 4       12     76.3   73.9  75.4   75.2  80.5     82.7     80.8    73.0    73.9
 5       13     57.1   54.0  57.8   53.9  63.7     65.2     68.7    50.7    55.3
 6       14     74.0   74.3  76.4   71.7  81.2     82.5     78.4    71.7    70.7
 7       15     70.9   61.4  70.9   61.2  74.5     75.2     71.7    61.5    62.1
 8       16     59.0   43.9  59.3   48.5  61.6     61.5     59.1    36.6    53.8
 9       17     46.9   46.1  56.4   41.1  57.0     59.1     51.7    36.9    35.9
10       18     59.9   63.1  65.1   54.3  64.1     64.4     65.2    51.0    56.8
11       19     58.5   51.0  66.0   55.6  60.7     63.1     60.9    50.2    53.8
12       20     61.7   53.9  63.3   53.9  65.3     61.7     60.3    50.1    51.0
13       21     62.4   53.9  63.4   55.8  67.7     67.3     61.6    54.0    56.7
14       22     61.9   54.6  60.4   53.3  65.1     64.0     61.6    55.1    56.6
15       23     54.4   46.2  57.5   50.7  56.2     60.8     54.5    49.7    49.7
16       24     56.8   55.3  57.8   52.4  60.9     62.2     57.1    50.8    51.4
17       25     53.8   42.9  56.5   51.2  56.3     60.7     52.4    45.0    44.1
18       26     54.0   49.5  55.4   48.8  55.6     61.9     53.4    47.2    47.0
# … with 38 more variables: Gunma &lt;dbl&gt;, Saitama &lt;dbl&gt;, Chiba &lt;dbl&gt;,
#   Tokyo &lt;dbl&gt;, Kanagawa &lt;dbl&gt;, Nigata &lt;dbl&gt;, Toyama &lt;dbl&gt;, Ishikawa &lt;dbl&gt;,
#   Fukui &lt;dbl&gt;, Yamanashi &lt;dbl&gt;, Nagano &lt;dbl&gt;, Gifu &lt;dbl&gt;, Shizuoka &lt;dbl&gt;,
#   Aichi &lt;dbl&gt;, Mie &lt;dbl&gt;, Shiga &lt;dbl&gt;, Kyoto &lt;dbl&gt;, Osaka &lt;dbl&gt;, Hyogo &lt;dbl&gt;,
#   Nara &lt;dbl&gt;, Wakayama &lt;dbl&gt;, Tottori &lt;dbl&gt;, Shimane &lt;dbl&gt;, Okayama &lt;dbl&gt;,
#   Hiroshima &lt;dbl&gt;, Yamaguchi &lt;dbl&gt;, Tokushima &lt;dbl&gt;, Kagawa &lt;dbl&gt;,
#   Ehime &lt;dbl&gt;, Kochi &lt;dbl&gt;, Fukuoka &lt;dbl&gt;, Saga &lt;dbl&gt;, Nagasaki &lt;dbl&gt;, …
# ℹ Use `colnames()` to see all variable names</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1"></a>ci_df <span class="ot">&lt;-</span> ci_df <span class="sc">|&gt;</span> </span>
<span id="cb81-2"><a href="#cb81-2"></a>  <span class="co"># Tottori列を最先端へ（= Election列より前）</span></span>
<span id="cb81-3"><a href="#cb81-3"></a>  <span class="fu">relocate</span>(Tottori, <span class="at">.before =</span> Election) <span class="sc">|&gt;</span></span>
<span id="cb81-4"><a href="#cb81-4"></a>  <span class="co"># その他の処置群とElection列を除外</span></span>
<span id="cb81-5"><a href="#cb81-5"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(Election, Shimane, Tokushima, Kochi))</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1"></a>ci_fit <span class="ot">&lt;-</span> ci_df <span class="sc">|&gt;</span></span>
<span id="cb82-2"><a href="#cb82-2"></a>  <span class="fu">CausalImpact</span>(<span class="at">pre.period =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">15</span>), <span class="at">post.period =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">18</span>))</span>
<span id="cb82-3"><a href="#cb82-3"></a></span>
<span id="cb82-4"><a href="#cb82-4"></a>ci_fit</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Posterior inference {CausalImpact}

                         Average         Cumulative   
Actual                   52              155          
Prediction (s.d.)        61 (3.6)        183 (10.9)   
95% CI                   [54, 68]        [162, 204]   
                                                      
Absolute effect (s.d.)   -9.4 (3.6)      -28.1 (10.9) 
95% CI                   [-16, -2.2]     [-49, -6.5]  
                                                      
Relative effect (s.d.)   -15% (5.9%)     -15% (5.9%)  
95% CI                   [-27%, -3.6%]   [-27%, -3.6%]

Posterior tail-area probability p:   0.01308
Posterior prob. of a causal effect:  98.692%

For more details, type: summary(impact, "report")</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1"></a><span class="fu">plot</span>(ci_fit)</span></code><button title="コピーする" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<p>宋はCausalImpactの便利さ（=統制群すら必要としない点、{CausalImpact}パッケージの使いやすさ）は認めるものの、まだまだ改善の余地があると考えているので、ここまでに紹介させて頂きたい。詳細な紹介についてはill-identifiedさんの<a href="https://ill-identified.hatenablog.com/entry/2019/10/09/120000">記事</a>と<a href="https://github.com/Gedevan-Aleksizde/20190728_DID">コード</a>が詳しい。</p>


</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">注</h2>

<ol>
<li id="fn1" role="doc-endnote"><p><code>fixed_effects</code>引数でなく、回帰式に説明変数として指定しても結果は同じである。しかし、回帰式に書く場合、固定効果の推定値も全て出力され、推定結果が非常に長くなる。しかし、固定効果の推定値は論文内で報告することもない。<code>fixed_effects</code>で指定すると、それらの結果は省略される。<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>{gsynth}は通常のSCMでなく、一般化SCMを実装したパッケージである。通常のSCMは処置群は1つのみに使えるが、一般化SCMは処置群が複数あっても使える。一般化SCMについてはYiqing Xu. 2017. “<a href="https://www.cambridge.org/core/journals/political-analysis/article/generalized-synthetic-control-method-causal-inference-with-interactive-fixed-effects-models/B63A8BD7C239DD4141C67DA10CD0E4F3#article">Generalized Synthetic Control Method: Causal Inference with Interactive Fixed Effects Models</a>,” <em>Political Analysis,</em> 25 (1): 57-76.を参照されたい。<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p>第7〜23回参院選のデータは<a href="http://db.cps.kutc.kansai-u.ac.jp/">参議院議員通常選挙データベース</a>からダウンロードしたものを架空したものであり、第24〜26回データは宋が手入力したものである。<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp(/https:\/\/www\.jaysong\.net\/kobe-ci\//);
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../material/matching.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">マッチング</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../material/rdd.html" class="pagination-link">
        <span class="nav-page-text">回帰不連続デザイン</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Copyright 2022, <a href="https://www.jaysong.net" target="_blank">Jaehyun Song</a>. Powered by <a href="https://quarto.org/" target="_blank">Quarto</a></div>   
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.jaysong.net">
      <i class="bi bi-house-fill" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/JaehyunSong">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>